// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.grafana.DataSourcePermissionArgs;
import com.pulumi.grafana.Utilities;
import com.pulumi.grafana.inputs.DataSourcePermissionState;
import com.pulumi.grafana.outputs.DataSourcePermissionPermission;
import java.lang.Integer;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="grafana:index/dataSourcePermission:DataSourcePermission")
public class DataSourcePermission extends com.pulumi.resources.CustomResource {
    /**
     * ID of the datasource to apply permissions to.
     * 
     */
    @Export(name="datasourceId", type=Integer.class, parameters={})
    private Output<Integer> datasourceId;

    /**
     * @return ID of the datasource to apply permissions to.
     * 
     */
    public Output<Integer> datasourceId() {
        return this.datasourceId;
    }
    /**
     * The permission items to add/update. Items that are omitted from the list will be removed.
     * 
     */
    @Export(name="permissions", type=List.class, parameters={DataSourcePermissionPermission.class})
    private Output<List<DataSourcePermissionPermission>> permissions;

    /**
     * @return The permission items to add/update. Items that are omitted from the list will be removed.
     * 
     */
    public Output<List<DataSourcePermissionPermission>> permissions() {
        return this.permissions;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DataSourcePermission(String name) {
        this(name, DataSourcePermissionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DataSourcePermission(String name, DataSourcePermissionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DataSourcePermission(String name, DataSourcePermissionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("grafana:index/dataSourcePermission:DataSourcePermission", name, args == null ? DataSourcePermissionArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DataSourcePermission(String name, Output<String> id, @Nullable DataSourcePermissionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("grafana:index/dataSourcePermission:DataSourcePermission", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DataSourcePermission get(String name, Output<String> id, @Nullable DataSourcePermissionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DataSourcePermission(name, id, state, options);
    }
}
