// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.grafana.FolderPermissionArgs;
import com.pulumi.grafana.Utilities;
import com.pulumi.grafana.inputs.FolderPermissionState;
import com.pulumi.grafana.outputs.FolderPermissionPermission;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="grafana:index/folderPermission:FolderPermission")
public class FolderPermission extends com.pulumi.resources.CustomResource {
    /**
     * The UID of the folder.
     * 
     */
    @Export(name="folderUid", type=String.class, parameters={})
    private Output<String> folderUid;

    /**
     * @return The UID of the folder.
     * 
     */
    public Output<String> folderUid() {
        return this.folderUid;
    }
    /**
     * The permission items to add/update. Items that are omitted from the list will be removed.
     * 
     */
    @Export(name="permissions", type=List.class, parameters={FolderPermissionPermission.class})
    private Output<List<FolderPermissionPermission>> permissions;

    /**
     * @return The permission items to add/update. Items that are omitted from the list will be removed.
     * 
     */
    public Output<List<FolderPermissionPermission>> permissions() {
        return this.permissions;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public FolderPermission(String name) {
        this(name, FolderPermissionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public FolderPermission(String name, FolderPermissionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public FolderPermission(String name, FolderPermissionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("grafana:index/folderPermission:FolderPermission", name, args == null ? FolderPermissionArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private FolderPermission(String name, Output<String> id, @Nullable FolderPermissionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("grafana:index/folderPermission:FolderPermission", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static FolderPermission get(String name, Output<String> id, @Nullable FolderPermissionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new FolderPermission(name, id, state, options);
    }
}
