// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.grafana.OutgoingWebhookArgs;
import com.pulumi.grafana.Utilities;
import com.pulumi.grafana.inputs.OutgoingWebhookState;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="grafana:index/outgoingWebhook:OutgoingWebhook")
public class OutgoingWebhook extends com.pulumi.resources.CustomResource {
    /**
     * The auth data of the webhook. Used in Authorization header instead of user/password auth.
     * 
     */
    @Export(name="authorizationHeader", type=String.class, parameters={})
    private Output</* @Nullable */ String> authorizationHeader;

    /**
     * @return The auth data of the webhook. Used in Authorization header instead of user/password auth.
     * 
     */
    public Output<Optional<String>> authorizationHeader() {
        return Codegen.optional(this.authorizationHeader);
    }
    /**
     * The data of the webhook.
     * 
     */
    @Export(name="data", type=String.class, parameters={})
    private Output</* @Nullable */ String> data;

    /**
     * @return The data of the webhook.
     * 
     */
    public Output<Optional<String>> data() {
        return Codegen.optional(this.data);
    }
    /**
     * Forwards whole payload of the alert to the webhook&#39;s url as POST data.
     * 
     */
    @Export(name="forwardWholePayload", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> forwardWholePayload;

    /**
     * @return Forwards whole payload of the alert to the webhook&#39;s url as POST data.
     * 
     */
    public Output<Optional<Boolean>> forwardWholePayload() {
        return Codegen.optional(this.forwardWholePayload);
    }
    /**
     * The name of the outgoing webhook.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The name of the outgoing webhook.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The auth data of the webhook. Used for Basic authentication
     * 
     */
    @Export(name="password", type=String.class, parameters={})
    private Output</* @Nullable */ String> password;

    /**
     * @return The auth data of the webhook. Used for Basic authentication
     * 
     */
    public Output<Optional<String>> password() {
        return Codegen.optional(this.password);
    }
    /**
     * The ID of the team.
     * 
     */
    @Export(name="teamId", type=String.class, parameters={})
    private Output</* @Nullable */ String> teamId;

    /**
     * @return The ID of the team.
     * 
     */
    public Output<Optional<String>> teamId() {
        return Codegen.optional(this.teamId);
    }
    /**
     * The webhook URL.
     * 
     */
    @Export(name="url", type=String.class, parameters={})
    private Output<String> url;

    /**
     * @return The webhook URL.
     * 
     */
    public Output<String> url() {
        return this.url;
    }
    /**
     * The auth data of the webhook. Used for Basic authentication.
     * 
     */
    @Export(name="user", type=String.class, parameters={})
    private Output</* @Nullable */ String> user;

    /**
     * @return The auth data of the webhook. Used for Basic authentication.
     * 
     */
    public Output<Optional<String>> user() {
        return Codegen.optional(this.user);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OutgoingWebhook(String name) {
        this(name, OutgoingWebhookArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OutgoingWebhook(String name, OutgoingWebhookArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OutgoingWebhook(String name, OutgoingWebhookArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("grafana:index/outgoingWebhook:OutgoingWebhook", name, args == null ? OutgoingWebhookArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private OutgoingWebhook(String name, Output<String> id, @Nullable OutgoingWebhookState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("grafana:index/outgoingWebhook:OutgoingWebhook", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OutgoingWebhook get(String name, Output<String> id, @Nullable OutgoingWebhookState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OutgoingWebhook(name, id, state, options);
    }
}
