// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ContactPointWebhook {
    private @Nullable String authorizationCredentials;
    private @Nullable String authorizationScheme;
    private @Nullable String basicAuthPassword;
    private @Nullable String basicAuthUser;
    private @Nullable Boolean disableResolveMessage;
    private @Nullable String httpMethod;
    private @Nullable Integer maxAlerts;
    private @Nullable Map<String,String> settings;
    private @Nullable String uid;
    private String url;

    private ContactPointWebhook() {}
    public Optional<String> authorizationCredentials() {
        return Optional.ofNullable(this.authorizationCredentials);
    }
    public Optional<String> authorizationScheme() {
        return Optional.ofNullable(this.authorizationScheme);
    }
    public Optional<String> basicAuthPassword() {
        return Optional.ofNullable(this.basicAuthPassword);
    }
    public Optional<String> basicAuthUser() {
        return Optional.ofNullable(this.basicAuthUser);
    }
    public Optional<Boolean> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }
    public Optional<String> httpMethod() {
        return Optional.ofNullable(this.httpMethod);
    }
    public Optional<Integer> maxAlerts() {
        return Optional.ofNullable(this.maxAlerts);
    }
    public Map<String,String> settings() {
        return this.settings == null ? Map.of() : this.settings;
    }
    public Optional<String> uid() {
        return Optional.ofNullable(this.uid);
    }
    public String url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ContactPointWebhook defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String authorizationCredentials;
        private @Nullable String authorizationScheme;
        private @Nullable String basicAuthPassword;
        private @Nullable String basicAuthUser;
        private @Nullable Boolean disableResolveMessage;
        private @Nullable String httpMethod;
        private @Nullable Integer maxAlerts;
        private @Nullable Map<String,String> settings;
        private @Nullable String uid;
        private String url;
        public Builder() {}
        public Builder(ContactPointWebhook defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.authorizationCredentials = defaults.authorizationCredentials;
    	      this.authorizationScheme = defaults.authorizationScheme;
    	      this.basicAuthPassword = defaults.basicAuthPassword;
    	      this.basicAuthUser = defaults.basicAuthUser;
    	      this.disableResolveMessage = defaults.disableResolveMessage;
    	      this.httpMethod = defaults.httpMethod;
    	      this.maxAlerts = defaults.maxAlerts;
    	      this.settings = defaults.settings;
    	      this.uid = defaults.uid;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder authorizationCredentials(@Nullable String authorizationCredentials) {
            this.authorizationCredentials = authorizationCredentials;
            return this;
        }
        @CustomType.Setter
        public Builder authorizationScheme(@Nullable String authorizationScheme) {
            this.authorizationScheme = authorizationScheme;
            return this;
        }
        @CustomType.Setter
        public Builder basicAuthPassword(@Nullable String basicAuthPassword) {
            this.basicAuthPassword = basicAuthPassword;
            return this;
        }
        @CustomType.Setter
        public Builder basicAuthUser(@Nullable String basicAuthUser) {
            this.basicAuthUser = basicAuthUser;
            return this;
        }
        @CustomType.Setter
        public Builder disableResolveMessage(@Nullable Boolean disableResolveMessage) {
            this.disableResolveMessage = disableResolveMessage;
            return this;
        }
        @CustomType.Setter
        public Builder httpMethod(@Nullable String httpMethod) {
            this.httpMethod = httpMethod;
            return this;
        }
        @CustomType.Setter
        public Builder maxAlerts(@Nullable Integer maxAlerts) {
            this.maxAlerts = maxAlerts;
            return this;
        }
        @CustomType.Setter
        public Builder settings(@Nullable Map<String,String> settings) {
            this.settings = settings;
            return this;
        }
        @CustomType.Setter
        public Builder uid(@Nullable String uid) {
            this.uid = uid;
            return this;
        }
        @CustomType.Setter
        public Builder url(String url) {
            this.url = Objects.requireNonNull(url);
            return this;
        }
        public ContactPointWebhook build() {
            final var o = new ContactPointWebhook();
            o.authorizationCredentials = authorizationCredentials;
            o.authorizationScheme = authorizationScheme;
            o.basicAuthPassword = basicAuthPassword;
            o.basicAuthUser = basicAuthUser;
            o.disableResolveMessage = disableResolveMessage;
            o.httpMethod = httpMethod;
            o.maxAlerts = maxAlerts;
            o.settings = settings;
            o.uid = uid;
            o.url = url;
            return o;
        }
    }
}
