// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ContactPointPagerduty {
    private @Nullable String class_;
    private @Nullable String component;
    private @Nullable Boolean disableResolveMessage;
    private @Nullable String group;
    private String integrationKey;
    private @Nullable Map<String,String> settings;
    private @Nullable String severity;
    private @Nullable String summary;
    private @Nullable String uid;

    private ContactPointPagerduty() {}
    public Optional<String> class_() {
        return Optional.ofNullable(this.class_);
    }
    public Optional<String> component() {
        return Optional.ofNullable(this.component);
    }
    public Optional<Boolean> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }
    public Optional<String> group() {
        return Optional.ofNullable(this.group);
    }
    public String integrationKey() {
        return this.integrationKey;
    }
    public Map<String,String> settings() {
        return this.settings == null ? Map.of() : this.settings;
    }
    public Optional<String> severity() {
        return Optional.ofNullable(this.severity);
    }
    public Optional<String> summary() {
        return Optional.ofNullable(this.summary);
    }
    public Optional<String> uid() {
        return Optional.ofNullable(this.uid);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ContactPointPagerduty defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String class_;
        private @Nullable String component;
        private @Nullable Boolean disableResolveMessage;
        private @Nullable String group;
        private String integrationKey;
        private @Nullable Map<String,String> settings;
        private @Nullable String severity;
        private @Nullable String summary;
        private @Nullable String uid;
        public Builder() {}
        public Builder(ContactPointPagerduty defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.class_ = defaults.class_;
    	      this.component = defaults.component;
    	      this.disableResolveMessage = defaults.disableResolveMessage;
    	      this.group = defaults.group;
    	      this.integrationKey = defaults.integrationKey;
    	      this.settings = defaults.settings;
    	      this.severity = defaults.severity;
    	      this.summary = defaults.summary;
    	      this.uid = defaults.uid;
        }

        @CustomType.Setter("class")
        public Builder class_(@Nullable String class_) {
            this.class_ = class_;
            return this;
        }
        @CustomType.Setter
        public Builder component(@Nullable String component) {
            this.component = component;
            return this;
        }
        @CustomType.Setter
        public Builder disableResolveMessage(@Nullable Boolean disableResolveMessage) {
            this.disableResolveMessage = disableResolveMessage;
            return this;
        }
        @CustomType.Setter
        public Builder group(@Nullable String group) {
            this.group = group;
            return this;
        }
        @CustomType.Setter
        public Builder integrationKey(String integrationKey) {
            this.integrationKey = Objects.requireNonNull(integrationKey);
            return this;
        }
        @CustomType.Setter
        public Builder settings(@Nullable Map<String,String> settings) {
            this.settings = settings;
            return this;
        }
        @CustomType.Setter
        public Builder severity(@Nullable String severity) {
            this.severity = severity;
            return this;
        }
        @CustomType.Setter
        public Builder summary(@Nullable String summary) {
            this.summary = summary;
            return this;
        }
        @CustomType.Setter
        public Builder uid(@Nullable String uid) {
            this.uid = uid;
            return this;
        }
        public ContactPointPagerduty build() {
            final var o = new ContactPointPagerduty();
            o.class_ = class_;
            o.component = component;
            o.disableResolveMessage = disableResolveMessage;
            o.group = group;
            o.integrationKey = integrationKey;
            o.settings = settings;
            o.severity = severity;
            o.summary = summary;
            o.uid = uid;
            return o;
        }
    }
}
