// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ContactPointSlack {
    private @Nullable Boolean disableResolveMessage;
    private @Nullable String endpointUrl;
    private @Nullable String iconEmoji;
    private @Nullable String iconUrl;
    private @Nullable String mentionChannel;
    private @Nullable String mentionGroups;
    private @Nullable String mentionUsers;
    private @Nullable String recipient;
    private @Nullable Map<String,String> settings;
    private @Nullable String text;
    private @Nullable String title;
    private @Nullable String token;
    private @Nullable String uid;
    private @Nullable String url;
    private @Nullable String username;

    private ContactPointSlack() {}
    public Optional<Boolean> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }
    public Optional<String> endpointUrl() {
        return Optional.ofNullable(this.endpointUrl);
    }
    public Optional<String> iconEmoji() {
        return Optional.ofNullable(this.iconEmoji);
    }
    public Optional<String> iconUrl() {
        return Optional.ofNullable(this.iconUrl);
    }
    public Optional<String> mentionChannel() {
        return Optional.ofNullable(this.mentionChannel);
    }
    public Optional<String> mentionGroups() {
        return Optional.ofNullable(this.mentionGroups);
    }
    public Optional<String> mentionUsers() {
        return Optional.ofNullable(this.mentionUsers);
    }
    public Optional<String> recipient() {
        return Optional.ofNullable(this.recipient);
    }
    public Map<String,String> settings() {
        return this.settings == null ? Map.of() : this.settings;
    }
    public Optional<String> text() {
        return Optional.ofNullable(this.text);
    }
    public Optional<String> title() {
        return Optional.ofNullable(this.title);
    }
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }
    public Optional<String> uid() {
        return Optional.ofNullable(this.uid);
    }
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }
    public Optional<String> username() {
        return Optional.ofNullable(this.username);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ContactPointSlack defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean disableResolveMessage;
        private @Nullable String endpointUrl;
        private @Nullable String iconEmoji;
        private @Nullable String iconUrl;
        private @Nullable String mentionChannel;
        private @Nullable String mentionGroups;
        private @Nullable String mentionUsers;
        private @Nullable String recipient;
        private @Nullable Map<String,String> settings;
        private @Nullable String text;
        private @Nullable String title;
        private @Nullable String token;
        private @Nullable String uid;
        private @Nullable String url;
        private @Nullable String username;
        public Builder() {}
        public Builder(ContactPointSlack defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disableResolveMessage = defaults.disableResolveMessage;
    	      this.endpointUrl = defaults.endpointUrl;
    	      this.iconEmoji = defaults.iconEmoji;
    	      this.iconUrl = defaults.iconUrl;
    	      this.mentionChannel = defaults.mentionChannel;
    	      this.mentionGroups = defaults.mentionGroups;
    	      this.mentionUsers = defaults.mentionUsers;
    	      this.recipient = defaults.recipient;
    	      this.settings = defaults.settings;
    	      this.text = defaults.text;
    	      this.title = defaults.title;
    	      this.token = defaults.token;
    	      this.uid = defaults.uid;
    	      this.url = defaults.url;
    	      this.username = defaults.username;
        }

        @CustomType.Setter
        public Builder disableResolveMessage(@Nullable Boolean disableResolveMessage) {
            this.disableResolveMessage = disableResolveMessage;
            return this;
        }
        @CustomType.Setter
        public Builder endpointUrl(@Nullable String endpointUrl) {
            this.endpointUrl = endpointUrl;
            return this;
        }
        @CustomType.Setter
        public Builder iconEmoji(@Nullable String iconEmoji) {
            this.iconEmoji = iconEmoji;
            return this;
        }
        @CustomType.Setter
        public Builder iconUrl(@Nullable String iconUrl) {
            this.iconUrl = iconUrl;
            return this;
        }
        @CustomType.Setter
        public Builder mentionChannel(@Nullable String mentionChannel) {
            this.mentionChannel = mentionChannel;
            return this;
        }
        @CustomType.Setter
        public Builder mentionGroups(@Nullable String mentionGroups) {
            this.mentionGroups = mentionGroups;
            return this;
        }
        @CustomType.Setter
        public Builder mentionUsers(@Nullable String mentionUsers) {
            this.mentionUsers = mentionUsers;
            return this;
        }
        @CustomType.Setter
        public Builder recipient(@Nullable String recipient) {
            this.recipient = recipient;
            return this;
        }
        @CustomType.Setter
        public Builder settings(@Nullable Map<String,String> settings) {
            this.settings = settings;
            return this;
        }
        @CustomType.Setter
        public Builder text(@Nullable String text) {
            this.text = text;
            return this;
        }
        @CustomType.Setter
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }
        @CustomType.Setter
        public Builder token(@Nullable String token) {
            this.token = token;
            return this;
        }
        @CustomType.Setter
        public Builder uid(@Nullable String uid) {
            this.uid = uid;
            return this;
        }
        @CustomType.Setter
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }
        @CustomType.Setter
        public Builder username(@Nullable String username) {
            this.username = username;
            return this;
        }
        public ContactPointSlack build() {
            final var o = new ContactPointSlack();
            o.disableResolveMessage = disableResolveMessage;
            o.endpointUrl = endpointUrl;
            o.iconEmoji = iconEmoji;
            o.iconUrl = iconUrl;
            o.mentionChannel = mentionChannel;
            o.mentionGroups = mentionGroups;
            o.mentionUsers = mentionUsers;
            o.recipient = recipient;
            o.settings = settings;
            o.text = text;
            o.title = title;
            o.token = token;
            o.uid = uid;
            o.url = url;
            o.username = username;
            return o;
        }
    }
}
