// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.grafana.outputs.MuteTimingIntervalTime;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class MuteTimingInterval {
    private @Nullable List<String> daysOfMonths;
    private @Nullable List<String> months;
    private @Nullable List<MuteTimingIntervalTime> times;
    private @Nullable List<String> weekdays;
    private @Nullable List<String> years;

    private MuteTimingInterval() {}
    public List<String> daysOfMonths() {
        return this.daysOfMonths == null ? List.of() : this.daysOfMonths;
    }
    public List<String> months() {
        return this.months == null ? List.of() : this.months;
    }
    public List<MuteTimingIntervalTime> times() {
        return this.times == null ? List.of() : this.times;
    }
    public List<String> weekdays() {
        return this.weekdays == null ? List.of() : this.weekdays;
    }
    public List<String> years() {
        return this.years == null ? List.of() : this.years;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(MuteTimingInterval defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> daysOfMonths;
        private @Nullable List<String> months;
        private @Nullable List<MuteTimingIntervalTime> times;
        private @Nullable List<String> weekdays;
        private @Nullable List<String> years;
        public Builder() {}
        public Builder(MuteTimingInterval defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.daysOfMonths = defaults.daysOfMonths;
    	      this.months = defaults.months;
    	      this.times = defaults.times;
    	      this.weekdays = defaults.weekdays;
    	      this.years = defaults.years;
        }

        @CustomType.Setter
        public Builder daysOfMonths(@Nullable List<String> daysOfMonths) {
            this.daysOfMonths = daysOfMonths;
            return this;
        }
        public Builder daysOfMonths(String... daysOfMonths) {
            return daysOfMonths(List.of(daysOfMonths));
        }
        @CustomType.Setter
        public Builder months(@Nullable List<String> months) {
            this.months = months;
            return this;
        }
        public Builder months(String... months) {
            return months(List.of(months));
        }
        @CustomType.Setter
        public Builder times(@Nullable List<MuteTimingIntervalTime> times) {
            this.times = times;
            return this;
        }
        public Builder times(MuteTimingIntervalTime... times) {
            return times(List.of(times));
        }
        @CustomType.Setter
        public Builder weekdays(@Nullable List<String> weekdays) {
            this.weekdays = weekdays;
            return this;
        }
        public Builder weekdays(String... weekdays) {
            return weekdays(List.of(weekdays));
        }
        @CustomType.Setter
        public Builder years(@Nullable List<String> years) {
            this.years = years;
            return this;
        }
        public Builder years(String... years) {
            return years(List.of(years));
        }
        public MuteTimingInterval build() {
            final var o = new MuteTimingInterval();
            o.daysOfMonths = daysOfMonths;
            o.months = months;
            o.times = times;
            o.weekdays = weekdays;
            o.years = years;
            return o;
        }
    }
}
