// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.grafana.outputs.OncallIntegrationDefaultRouteSlack;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class OncallIntegrationDefaultRoute {
    private @Nullable String escalationChainId;
    private @Nullable String id;
    private @Nullable OncallIntegrationDefaultRouteSlack slack;

    private OncallIntegrationDefaultRoute() {}
    public Optional<String> escalationChainId() {
        return Optional.ofNullable(this.escalationChainId);
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<OncallIntegrationDefaultRouteSlack> slack() {
        return Optional.ofNullable(this.slack);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OncallIntegrationDefaultRoute defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String escalationChainId;
        private @Nullable String id;
        private @Nullable OncallIntegrationDefaultRouteSlack slack;
        public Builder() {}
        public Builder(OncallIntegrationDefaultRoute defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.escalationChainId = defaults.escalationChainId;
    	      this.id = defaults.id;
    	      this.slack = defaults.slack;
        }

        @CustomType.Setter
        public Builder escalationChainId(@Nullable String escalationChainId) {
            this.escalationChainId = escalationChainId;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder slack(@Nullable OncallIntegrationDefaultRouteSlack slack) {
            this.slack = slack;
            return this;
        }
        public OncallIntegrationDefaultRoute build() {
            final var o = new OncallIntegrationDefaultRoute();
            o.escalationChainId = escalationChainId;
            o.id = id;
            o.slack = slack;
            return o;
        }
    }
}
