// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class OncallRouteSlack {
    private String channelId;

    private OncallRouteSlack() {}
    public String channelId() {
        return this.channelId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OncallRouteSlack defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String channelId;
        public Builder() {}
        public Builder(OncallRouteSlack defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channelId = defaults.channelId;
        }

        @CustomType.Setter
        public Builder channelId(String channelId) {
            this.channelId = Objects.requireNonNull(channelId);
            return this;
        }
        public OncallRouteSlack build() {
            final var o = new OncallRouteSlack();
            o.channelId = channelId;
            return o;
        }
    }
}
