// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ReportSchedule {
    private @Nullable String customInterval;
    private @Nullable String endTime;
    private String frequency;
    private @Nullable String startTime;
    private @Nullable Boolean workdaysOnly;

    private ReportSchedule() {}
    public Optional<String> customInterval() {
        return Optional.ofNullable(this.customInterval);
    }
    public Optional<String> endTime() {
        return Optional.ofNullable(this.endTime);
    }
    public String frequency() {
        return this.frequency;
    }
    public Optional<String> startTime() {
        return Optional.ofNullable(this.startTime);
    }
    public Optional<Boolean> workdaysOnly() {
        return Optional.ofNullable(this.workdaysOnly);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ReportSchedule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String customInterval;
        private @Nullable String endTime;
        private String frequency;
        private @Nullable String startTime;
        private @Nullable Boolean workdaysOnly;
        public Builder() {}
        public Builder(ReportSchedule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.customInterval = defaults.customInterval;
    	      this.endTime = defaults.endTime;
    	      this.frequency = defaults.frequency;
    	      this.startTime = defaults.startTime;
    	      this.workdaysOnly = defaults.workdaysOnly;
        }

        @CustomType.Setter
        public Builder customInterval(@Nullable String customInterval) {
            this.customInterval = customInterval;
            return this;
        }
        @CustomType.Setter
        public Builder endTime(@Nullable String endTime) {
            this.endTime = endTime;
            return this;
        }
        @CustomType.Setter
        public Builder frequency(String frequency) {
            this.frequency = Objects.requireNonNull(frequency);
            return this;
        }
        @CustomType.Setter
        public Builder startTime(@Nullable String startTime) {
            this.startTime = startTime;
            return this;
        }
        @CustomType.Setter
        public Builder workdaysOnly(@Nullable Boolean workdaysOnly) {
            this.workdaysOnly = workdaysOnly;
            return this;
        }
        public ReportSchedule build() {
            final var o = new ReportSchedule();
            o.customInterval = customInterval;
            o.endTime = endTime;
            o.frequency = frequency;
            o.startTime = startTime;
            o.workdaysOnly = workdaysOnly;
            return o;
        }
    }
}
