// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class ContactPointPagerduty
    {
        public readonly string? Class;
        public readonly string? Component;
        public readonly bool? DisableResolveMessage;
        public readonly string? Group;
        public readonly string IntegrationKey;
        public readonly ImmutableDictionary<string, string>? Settings;
        public readonly string? Severity;
        public readonly string? Summary;
        public readonly string? Uid;

        [OutputConstructor]
        private ContactPointPagerduty(
            string? @class,

            string? component,

            bool? disableResolveMessage,

            string? group,

            string integrationKey,

            ImmutableDictionary<string, string>? settings,

            string? severity,

            string? summary,

            string? uid)
        {
            Class = @class;
            Component = component;
            DisableResolveMessage = disableResolveMessage;
            Group = group;
            IntegrationKey = integrationKey;
            Settings = settings;
            Severity = severity;
            Summary = summary;
            Uid = uid;
        }
    }
}
