// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class ContactPointSlack
    {
        public readonly bool? DisableResolveMessage;
        public readonly string? EndpointUrl;
        public readonly string? IconEmoji;
        public readonly string? IconUrl;
        public readonly string? MentionChannel;
        public readonly string? MentionGroups;
        public readonly string? MentionUsers;
        public readonly string? Recipient;
        public readonly ImmutableDictionary<string, string>? Settings;
        public readonly string? Text;
        public readonly string? Title;
        public readonly string? Token;
        public readonly string? Uid;
        public readonly string? Url;
        public readonly string? Username;

        [OutputConstructor]
        private ContactPointSlack(
            bool? disableResolveMessage,

            string? endpointUrl,

            string? iconEmoji,

            string? iconUrl,

            string? mentionChannel,

            string? mentionGroups,

            string? mentionUsers,

            string? recipient,

            ImmutableDictionary<string, string>? settings,

            string? text,

            string? title,

            string? token,

            string? uid,

            string? url,

            string? username)
        {
            DisableResolveMessage = disableResolveMessage;
            EndpointUrl = endpointUrl;
            IconEmoji = iconEmoji;
            IconUrl = iconUrl;
            MentionChannel = mentionChannel;
            MentionGroups = mentionGroups;
            MentionUsers = mentionUsers;
            Recipient = recipient;
            Settings = settings;
            Text = text;
            Title = title;
            Token = token;
            Uid = uid;
            Url = url;
            Username = username;
        }
    }
}
