// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class DataSourceJsonData
    {
        public readonly string? AssumeRoleArn;
        public readonly string? AuthType;
        public readonly string? AuthenticationType;
        public readonly string? Catalog;
        public readonly string? ClientEmail;
        public readonly string? ClientId;
        public readonly string? CloudName;
        public readonly int? ConnMaxLifetime;
        public readonly string? CustomMetricsNamespaces;
        public readonly string? Database;
        public readonly string? DefaultBucket;
        public readonly string? DefaultProject;
        public readonly string? DefaultRegion;
        public readonly ImmutableArray<Outputs.DataSourceJsonDataDerivedField> DerivedFields;
        public readonly string? Encrypt;
        public readonly string? EsVersion;
        public readonly string? ExternalId;
        public readonly string? GithubUrl;
        public readonly string? GraphiteVersion;
        public readonly string? HttpMethod;
        public readonly string? Implementation;
        public readonly string? Interval;
        public readonly string? LogLevelField;
        public readonly string? LogMessageField;
        public readonly bool? ManageAlerts;
        public readonly int? MaxConcurrentShardRequests;
        public readonly int? MaxIdleConns;
        public readonly int? MaxLines;
        public readonly int? MaxOpenConns;
        public readonly string? OrgSlug;
        public readonly string? Organization;
        public readonly string? OutputLocation;
        public readonly int? PostgresVersion;
        public readonly string? Profile;
        public readonly string? QueryTimeout;
        public readonly string? Sigv4AssumeRoleArn;
        public readonly bool? Sigv4Auth;
        public readonly string? Sigv4AuthType;
        public readonly string? Sigv4ExternalId;
        public readonly string? Sigv4Profile;
        public readonly string? Sigv4Region;
        public readonly string? SslMode;
        public readonly string? SubscriptionId;
        public readonly string? TenantId;
        public readonly string? TimeField;
        public readonly string? TimeInterval;
        public readonly bool? Timescaledb;
        public readonly bool? TlsAuth;
        public readonly bool? TlsAuthWithCaCert;
        public readonly string? TlsConfigurationMethod;
        public readonly bool? TlsSkipVerify;
        public readonly string? TokenUri;
        public readonly string? TracingDatasourceUid;
        public readonly int? TsdbResolution;
        public readonly int? TsdbVersion;
        public readonly string? Version;
        public readonly string? Workgroup;
        public readonly bool? XpackEnabled;

        [OutputConstructor]
        private DataSourceJsonData(
            string? assumeRoleArn,

            string? authType,

            string? authenticationType,

            string? catalog,

            string? clientEmail,

            string? clientId,

            string? cloudName,

            int? connMaxLifetime,

            string? customMetricsNamespaces,

            string? database,

            string? defaultBucket,

            string? defaultProject,

            string? defaultRegion,

            ImmutableArray<Outputs.DataSourceJsonDataDerivedField> derivedFields,

            string? encrypt,

            string? esVersion,

            string? externalId,

            string? githubUrl,

            string? graphiteVersion,

            string? httpMethod,

            string? implementation,

            string? interval,

            string? logLevelField,

            string? logMessageField,

            bool? manageAlerts,

            int? maxConcurrentShardRequests,

            int? maxIdleConns,

            int? maxLines,

            int? maxOpenConns,

            string? orgSlug,

            string? organization,

            string? outputLocation,

            int? postgresVersion,

            string? profile,

            string? queryTimeout,

            string? sigv4AssumeRoleArn,

            bool? sigv4Auth,

            string? sigv4AuthType,

            string? sigv4ExternalId,

            string? sigv4Profile,

            string? sigv4Region,

            string? sslMode,

            string? subscriptionId,

            string? tenantId,

            string? timeField,

            string? timeInterval,

            bool? timescaledb,

            bool? tlsAuth,

            bool? tlsAuthWithCaCert,

            string? tlsConfigurationMethod,

            bool? tlsSkipVerify,

            string? tokenUri,

            string? tracingDatasourceUid,

            int? tsdbResolution,

            int? tsdbVersion,

            string? version,

            string? workgroup,

            bool? xpackEnabled)
        {
            AssumeRoleArn = assumeRoleArn;
            AuthType = authType;
            AuthenticationType = authenticationType;
            Catalog = catalog;
            ClientEmail = clientEmail;
            ClientId = clientId;
            CloudName = cloudName;
            ConnMaxLifetime = connMaxLifetime;
            CustomMetricsNamespaces = customMetricsNamespaces;
            Database = database;
            DefaultBucket = defaultBucket;
            DefaultProject = defaultProject;
            DefaultRegion = defaultRegion;
            DerivedFields = derivedFields;
            Encrypt = encrypt;
            EsVersion = esVersion;
            ExternalId = externalId;
            GithubUrl = githubUrl;
            GraphiteVersion = graphiteVersion;
            HttpMethod = httpMethod;
            Implementation = implementation;
            Interval = interval;
            LogLevelField = logLevelField;
            LogMessageField = logMessageField;
            ManageAlerts = manageAlerts;
            MaxConcurrentShardRequests = maxConcurrentShardRequests;
            MaxIdleConns = maxIdleConns;
            MaxLines = maxLines;
            MaxOpenConns = maxOpenConns;
            OrgSlug = orgSlug;
            Organization = organization;
            OutputLocation = outputLocation;
            PostgresVersion = postgresVersion;
            Profile = profile;
            QueryTimeout = queryTimeout;
            Sigv4AssumeRoleArn = sigv4AssumeRoleArn;
            Sigv4Auth = sigv4Auth;
            Sigv4AuthType = sigv4AuthType;
            Sigv4ExternalId = sigv4ExternalId;
            Sigv4Profile = sigv4Profile;
            Sigv4Region = sigv4Region;
            SslMode = sslMode;
            SubscriptionId = subscriptionId;
            TenantId = tenantId;
            TimeField = timeField;
            TimeInterval = timeInterval;
            Timescaledb = timescaledb;
            TlsAuth = tlsAuth;
            TlsAuthWithCaCert = tlsAuthWithCaCert;
            TlsConfigurationMethod = tlsConfigurationMethod;
            TlsSkipVerify = tlsSkipVerify;
            TokenUri = tokenUri;
            TracingDatasourceUid = tracingDatasourceUid;
            TsdbResolution = tsdbResolution;
            TsdbVersion = tsdbVersion;
            Version = version;
            Workgroup = workgroup;
            XpackEnabled = xpackEnabled;
        }
    }
}
