// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class NotificationPolicyPolicyPolicyPolicyPolicy
    {
        public readonly string ContactPoint;
        public readonly bool? Continue;
        public readonly ImmutableArray<string> GroupBies;
        public readonly string? GroupInterval;
        public readonly string? GroupWait;
        public readonly ImmutableArray<Outputs.NotificationPolicyPolicyPolicyPolicyPolicyMatcher> Matchers;
        public readonly ImmutableArray<string> MuteTimings;
        public readonly string? RepeatInterval;

        [OutputConstructor]
        private NotificationPolicyPolicyPolicyPolicyPolicy(
            string contactPoint,

            bool? @continue,

            ImmutableArray<string> groupBies,

            string? groupInterval,

            string? groupWait,

            ImmutableArray<Outputs.NotificationPolicyPolicyPolicyPolicyPolicyMatcher> matchers,

            ImmutableArray<string> muteTimings,

            string? repeatInterval)
        {
            ContactPoint = contactPoint;
            Continue = @continue;
            GroupBies = groupBies;
            GroupInterval = groupInterval;
            GroupWait = groupWait;
            Matchers = matchers;
            MuteTimings = muteTimings;
            RepeatInterval = repeatInterval;
        }
    }
}
