// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class OncallIntegrationDefaultRoute
    {
        /// <summary>
        /// The ID of the escalation chain.
        /// </summary>
        public readonly string? EscalationChainId;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Slack-specific settings for a route.
        /// </summary>
        public readonly Outputs.OncallIntegrationDefaultRouteSlack? Slack;

        [OutputConstructor]
        private OncallIntegrationDefaultRoute(
            string? escalationChainId,

            string? id,

            Outputs.OncallIntegrationDefaultRouteSlack? slack)
        {
            EscalationChainId = escalationChainId;
            Id = id;
            Slack = slack;
        }
    }
}
