// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class ReportSchedule
    {
        public readonly string? CustomInterval;
        public readonly string? EndTime;
        public readonly string Frequency;
        public readonly string? StartTime;
        public readonly bool? WorkdaysOnly;

        [OutputConstructor]
        private ReportSchedule(
            string? customInterval,

            string? endTime,

            string frequency,

            string? startTime,

            bool? workdaysOnly)
        {
            CustomInterval = customInterval;
            EndTime = endTime;
            Frequency = frequency;
            StartTime = startTime;
            WorkdaysOnly = workdaysOnly;
        }
    }
}
