// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class RuleGroupRule
    {
        public readonly ImmutableDictionary<string, string>? Annotations;
        public readonly string Condition;
        public readonly ImmutableArray<Outputs.RuleGroupRuleData> Datas;
        public readonly string? ExecErrState;
        public readonly string? For;
        public readonly ImmutableDictionary<string, string>? Labels;
        public readonly string Name;
        public readonly string? NoDataState;
        public readonly string? Uid;

        [OutputConstructor]
        private RuleGroupRule(
            ImmutableDictionary<string, string>? annotations,

            string condition,

            ImmutableArray<Outputs.RuleGroupRuleData> datas,

            string? execErrState,

            string? @for,

            ImmutableDictionary<string, string>? labels,

            string name,

            string? noDataState,

            string? uid)
        {
            Annotations = annotations;
            Condition = condition;
            Datas = datas;
            ExecErrState = execErrState;
            For = @for;
            Labels = labels;
            Name = name;
            NoDataState = noDataState;
            Uid = uid;
        }
    }
}
