// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BuiltinRoleAssignmentRoleArgs extends com.pulumi.resources.ResourceArgs {

    public static final BuiltinRoleAssignmentRoleArgs Empty = new BuiltinRoleAssignmentRoleArgs();

    @Import(name="global")
    private @Nullable Output<Boolean> global;

    public Optional<Output<Boolean>> global() {
        return Optional.ofNullable(this.global);
    }

    @Import(name="uid", required=true)
    private Output<String> uid;

    public Output<String> uid() {
        return this.uid;
    }

    private BuiltinRoleAssignmentRoleArgs() {}

    private BuiltinRoleAssignmentRoleArgs(BuiltinRoleAssignmentRoleArgs $) {
        this.global = $.global;
        this.uid = $.uid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BuiltinRoleAssignmentRoleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BuiltinRoleAssignmentRoleArgs $;

        public Builder() {
            $ = new BuiltinRoleAssignmentRoleArgs();
        }

        public Builder(BuiltinRoleAssignmentRoleArgs defaults) {
            $ = new BuiltinRoleAssignmentRoleArgs(Objects.requireNonNull(defaults));
        }

        public Builder global(@Nullable Output<Boolean> global) {
            $.global = global;
            return this;
        }

        public Builder global(Boolean global) {
            return global(Output.of(global));
        }

        public Builder uid(Output<String> uid) {
            $.uid = uid;
            return this;
        }

        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        public BuiltinRoleAssignmentRoleArgs build() {
            $.uid = Objects.requireNonNull($.uid, "expected parameter 'uid' to be non-null");
            return $;
        }
    }

}
