// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContactPointKafkaArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContactPointKafkaArgs Empty = new ContactPointKafkaArgs();

    @Import(name="disableResolveMessage")
    private @Nullable Output<Boolean> disableResolveMessage;

    public Optional<Output<Boolean>> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }

    @Import(name="restProxyUrl", required=true)
    private Output<String> restProxyUrl;

    public Output<String> restProxyUrl() {
        return this.restProxyUrl;
    }

    @Import(name="settings")
    private @Nullable Output<Map<String,String>> settings;

    public Optional<Output<Map<String,String>>> settings() {
        return Optional.ofNullable(this.settings);
    }

    @Import(name="topic", required=true)
    private Output<String> topic;

    public Output<String> topic() {
        return this.topic;
    }

    @Import(name="uid")
    private @Nullable Output<String> uid;

    public Optional<Output<String>> uid() {
        return Optional.ofNullable(this.uid);
    }

    private ContactPointKafkaArgs() {}

    private ContactPointKafkaArgs(ContactPointKafkaArgs $) {
        this.disableResolveMessage = $.disableResolveMessage;
        this.restProxyUrl = $.restProxyUrl;
        this.settings = $.settings;
        this.topic = $.topic;
        this.uid = $.uid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContactPointKafkaArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContactPointKafkaArgs $;

        public Builder() {
            $ = new ContactPointKafkaArgs();
        }

        public Builder(ContactPointKafkaArgs defaults) {
            $ = new ContactPointKafkaArgs(Objects.requireNonNull(defaults));
        }

        public Builder disableResolveMessage(@Nullable Output<Boolean> disableResolveMessage) {
            $.disableResolveMessage = disableResolveMessage;
            return this;
        }

        public Builder disableResolveMessage(Boolean disableResolveMessage) {
            return disableResolveMessage(Output.of(disableResolveMessage));
        }

        public Builder restProxyUrl(Output<String> restProxyUrl) {
            $.restProxyUrl = restProxyUrl;
            return this;
        }

        public Builder restProxyUrl(String restProxyUrl) {
            return restProxyUrl(Output.of(restProxyUrl));
        }

        public Builder settings(@Nullable Output<Map<String,String>> settings) {
            $.settings = settings;
            return this;
        }

        public Builder settings(Map<String,String> settings) {
            return settings(Output.of(settings));
        }

        public Builder topic(Output<String> topic) {
            $.topic = topic;
            return this;
        }

        public Builder topic(String topic) {
            return topic(Output.of(topic));
        }

        public Builder uid(@Nullable Output<String> uid) {
            $.uid = uid;
            return this;
        }

        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        public ContactPointKafkaArgs build() {
            $.restProxyUrl = Objects.requireNonNull($.restProxyUrl, "expected parameter 'restProxyUrl' to be non-null");
            $.topic = Objects.requireNonNull($.topic, "expected parameter 'topic' to be non-null");
            return $;
        }
    }

}
