// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContactPointOpsgenyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContactPointOpsgenyArgs Empty = new ContactPointOpsgenyArgs();

    @Import(name="apiKey", required=true)
    private Output<String> apiKey;

    public Output<String> apiKey() {
        return this.apiKey;
    }

    @Import(name="autoClose")
    private @Nullable Output<Boolean> autoClose;

    public Optional<Output<Boolean>> autoClose() {
        return Optional.ofNullable(this.autoClose);
    }

    @Import(name="description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="disableResolveMessage")
    private @Nullable Output<Boolean> disableResolveMessage;

    public Optional<Output<Boolean>> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }

    @Import(name="message")
    private @Nullable Output<String> message;

    public Optional<Output<String>> message() {
        return Optional.ofNullable(this.message);
    }

    @Import(name="overridePriority")
    private @Nullable Output<Boolean> overridePriority;

    public Optional<Output<Boolean>> overridePriority() {
        return Optional.ofNullable(this.overridePriority);
    }

    @Import(name="sendTagsAs")
    private @Nullable Output<String> sendTagsAs;

    public Optional<Output<String>> sendTagsAs() {
        return Optional.ofNullable(this.sendTagsAs);
    }

    @Import(name="settings")
    private @Nullable Output<Map<String,String>> settings;

    public Optional<Output<Map<String,String>>> settings() {
        return Optional.ofNullable(this.settings);
    }

    @Import(name="uid")
    private @Nullable Output<String> uid;

    public Optional<Output<String>> uid() {
        return Optional.ofNullable(this.uid);
    }

    @Import(name="url")
    private @Nullable Output<String> url;

    public Optional<Output<String>> url() {
        return Optional.ofNullable(this.url);
    }

    private ContactPointOpsgenyArgs() {}

    private ContactPointOpsgenyArgs(ContactPointOpsgenyArgs $) {
        this.apiKey = $.apiKey;
        this.autoClose = $.autoClose;
        this.description = $.description;
        this.disableResolveMessage = $.disableResolveMessage;
        this.message = $.message;
        this.overridePriority = $.overridePriority;
        this.sendTagsAs = $.sendTagsAs;
        this.settings = $.settings;
        this.uid = $.uid;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContactPointOpsgenyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContactPointOpsgenyArgs $;

        public Builder() {
            $ = new ContactPointOpsgenyArgs();
        }

        public Builder(ContactPointOpsgenyArgs defaults) {
            $ = new ContactPointOpsgenyArgs(Objects.requireNonNull(defaults));
        }

        public Builder apiKey(Output<String> apiKey) {
            $.apiKey = apiKey;
            return this;
        }

        public Builder apiKey(String apiKey) {
            return apiKey(Output.of(apiKey));
        }

        public Builder autoClose(@Nullable Output<Boolean> autoClose) {
            $.autoClose = autoClose;
            return this;
        }

        public Builder autoClose(Boolean autoClose) {
            return autoClose(Output.of(autoClose));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder disableResolveMessage(@Nullable Output<Boolean> disableResolveMessage) {
            $.disableResolveMessage = disableResolveMessage;
            return this;
        }

        public Builder disableResolveMessage(Boolean disableResolveMessage) {
            return disableResolveMessage(Output.of(disableResolveMessage));
        }

        public Builder message(@Nullable Output<String> message) {
            $.message = message;
            return this;
        }

        public Builder message(String message) {
            return message(Output.of(message));
        }

        public Builder overridePriority(@Nullable Output<Boolean> overridePriority) {
            $.overridePriority = overridePriority;
            return this;
        }

        public Builder overridePriority(Boolean overridePriority) {
            return overridePriority(Output.of(overridePriority));
        }

        public Builder sendTagsAs(@Nullable Output<String> sendTagsAs) {
            $.sendTagsAs = sendTagsAs;
            return this;
        }

        public Builder sendTagsAs(String sendTagsAs) {
            return sendTagsAs(Output.of(sendTagsAs));
        }

        public Builder settings(@Nullable Output<Map<String,String>> settings) {
            $.settings = settings;
            return this;
        }

        public Builder settings(Map<String,String> settings) {
            return settings(Output.of(settings));
        }

        public Builder uid(@Nullable Output<String> uid) {
            $.uid = uid;
            return this;
        }

        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        public Builder url(@Nullable Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public ContactPointOpsgenyArgs build() {
            $.apiKey = Objects.requireNonNull($.apiKey, "expected parameter 'apiKey' to be non-null");
            return $;
        }
    }

}
