// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContactPointWebhookArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContactPointWebhookArgs Empty = new ContactPointWebhookArgs();

    @Import(name="authorizationCredentials")
    private @Nullable Output<String> authorizationCredentials;

    public Optional<Output<String>> authorizationCredentials() {
        return Optional.ofNullable(this.authorizationCredentials);
    }

    @Import(name="authorizationScheme")
    private @Nullable Output<String> authorizationScheme;

    public Optional<Output<String>> authorizationScheme() {
        return Optional.ofNullable(this.authorizationScheme);
    }

    @Import(name="basicAuthPassword")
    private @Nullable Output<String> basicAuthPassword;

    public Optional<Output<String>> basicAuthPassword() {
        return Optional.ofNullable(this.basicAuthPassword);
    }

    @Import(name="basicAuthUser")
    private @Nullable Output<String> basicAuthUser;

    public Optional<Output<String>> basicAuthUser() {
        return Optional.ofNullable(this.basicAuthUser);
    }

    @Import(name="disableResolveMessage")
    private @Nullable Output<Boolean> disableResolveMessage;

    public Optional<Output<Boolean>> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }

    @Import(name="httpMethod")
    private @Nullable Output<String> httpMethod;

    public Optional<Output<String>> httpMethod() {
        return Optional.ofNullable(this.httpMethod);
    }

    @Import(name="maxAlerts")
    private @Nullable Output<Integer> maxAlerts;

    public Optional<Output<Integer>> maxAlerts() {
        return Optional.ofNullable(this.maxAlerts);
    }

    @Import(name="settings")
    private @Nullable Output<Map<String,String>> settings;

    public Optional<Output<Map<String,String>>> settings() {
        return Optional.ofNullable(this.settings);
    }

    @Import(name="uid")
    private @Nullable Output<String> uid;

    public Optional<Output<String>> uid() {
        return Optional.ofNullable(this.uid);
    }

    @Import(name="url", required=true)
    private Output<String> url;

    public Output<String> url() {
        return this.url;
    }

    private ContactPointWebhookArgs() {}

    private ContactPointWebhookArgs(ContactPointWebhookArgs $) {
        this.authorizationCredentials = $.authorizationCredentials;
        this.authorizationScheme = $.authorizationScheme;
        this.basicAuthPassword = $.basicAuthPassword;
        this.basicAuthUser = $.basicAuthUser;
        this.disableResolveMessage = $.disableResolveMessage;
        this.httpMethod = $.httpMethod;
        this.maxAlerts = $.maxAlerts;
        this.settings = $.settings;
        this.uid = $.uid;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContactPointWebhookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContactPointWebhookArgs $;

        public Builder() {
            $ = new ContactPointWebhookArgs();
        }

        public Builder(ContactPointWebhookArgs defaults) {
            $ = new ContactPointWebhookArgs(Objects.requireNonNull(defaults));
        }

        public Builder authorizationCredentials(@Nullable Output<String> authorizationCredentials) {
            $.authorizationCredentials = authorizationCredentials;
            return this;
        }

        public Builder authorizationCredentials(String authorizationCredentials) {
            return authorizationCredentials(Output.of(authorizationCredentials));
        }

        public Builder authorizationScheme(@Nullable Output<String> authorizationScheme) {
            $.authorizationScheme = authorizationScheme;
            return this;
        }

        public Builder authorizationScheme(String authorizationScheme) {
            return authorizationScheme(Output.of(authorizationScheme));
        }

        public Builder basicAuthPassword(@Nullable Output<String> basicAuthPassword) {
            $.basicAuthPassword = basicAuthPassword;
            return this;
        }

        public Builder basicAuthPassword(String basicAuthPassword) {
            return basicAuthPassword(Output.of(basicAuthPassword));
        }

        public Builder basicAuthUser(@Nullable Output<String> basicAuthUser) {
            $.basicAuthUser = basicAuthUser;
            return this;
        }

        public Builder basicAuthUser(String basicAuthUser) {
            return basicAuthUser(Output.of(basicAuthUser));
        }

        public Builder disableResolveMessage(@Nullable Output<Boolean> disableResolveMessage) {
            $.disableResolveMessage = disableResolveMessage;
            return this;
        }

        public Builder disableResolveMessage(Boolean disableResolveMessage) {
            return disableResolveMessage(Output.of(disableResolveMessage));
        }

        public Builder httpMethod(@Nullable Output<String> httpMethod) {
            $.httpMethod = httpMethod;
            return this;
        }

        public Builder httpMethod(String httpMethod) {
            return httpMethod(Output.of(httpMethod));
        }

        public Builder maxAlerts(@Nullable Output<Integer> maxAlerts) {
            $.maxAlerts = maxAlerts;
            return this;
        }

        public Builder maxAlerts(Integer maxAlerts) {
            return maxAlerts(Output.of(maxAlerts));
        }

        public Builder settings(@Nullable Output<Map<String,String>> settings) {
            $.settings = settings;
            return this;
        }

        public Builder settings(Map<String,String> settings) {
            return settings(Output.of(settings));
        }

        public Builder uid(@Nullable Output<String> uid) {
            $.uid = uid;
            return this;
        }

        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public ContactPointWebhookArgs build() {
            $.url = Objects.requireNonNull($.url, "expected parameter 'url' to be non-null");
            return $;
        }
    }

}
