// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContactPointVictoropArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContactPointVictoropArgs Empty = new ContactPointVictoropArgs();

    @Import(name="disableResolveMessage")
    private @Nullable Output<Boolean> disableResolveMessage;

    public Optional<Output<Boolean>> disableResolveMessage() {
        return Optional.ofNullable(this.disableResolveMessage);
    }

    @Import(name="messageType")
    private @Nullable Output<String> messageType;

    public Optional<Output<String>> messageType() {
        return Optional.ofNullable(this.messageType);
    }

    @Import(name="settings")
    private @Nullable Output<Map<String,String>> settings;

    public Optional<Output<Map<String,String>>> settings() {
        return Optional.ofNullable(this.settings);
    }

    @Import(name="uid")
    private @Nullable Output<String> uid;

    public Optional<Output<String>> uid() {
        return Optional.ofNullable(this.uid);
    }

    @Import(name="url", required=true)
    private Output<String> url;

    public Output<String> url() {
        return this.url;
    }

    private ContactPointVictoropArgs() {}

    private ContactPointVictoropArgs(ContactPointVictoropArgs $) {
        this.disableResolveMessage = $.disableResolveMessage;
        this.messageType = $.messageType;
        this.settings = $.settings;
        this.uid = $.uid;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContactPointVictoropArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContactPointVictoropArgs $;

        public Builder() {
            $ = new ContactPointVictoropArgs();
        }

        public Builder(ContactPointVictoropArgs defaults) {
            $ = new ContactPointVictoropArgs(Objects.requireNonNull(defaults));
        }

        public Builder disableResolveMessage(@Nullable Output<Boolean> disableResolveMessage) {
            $.disableResolveMessage = disableResolveMessage;
            return this;
        }

        public Builder disableResolveMessage(Boolean disableResolveMessage) {
            return disableResolveMessage(Output.of(disableResolveMessage));
        }

        public Builder messageType(@Nullable Output<String> messageType) {
            $.messageType = messageType;
            return this;
        }

        public Builder messageType(String messageType) {
            return messageType(Output.of(messageType));
        }

        public Builder settings(@Nullable Output<Map<String,String>> settings) {
            $.settings = settings;
            return this;
        }

        public Builder settings(Map<String,String> settings) {
            return settings(Output.of(settings));
        }

        public Builder uid(@Nullable Output<String> uid) {
            $.uid = uid;
            return this;
        }

        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public ContactPointVictoropArgs build() {
            $.url = Objects.requireNonNull($.url, "expected parameter 'url' to be non-null");
            return $;
        }
    }

}
