// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.grafana.inputs.DataSourceJsonDataDerivedFieldArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DataSourceJsonDataArgs extends com.pulumi.resources.ResourceArgs {

    public static final DataSourceJsonDataArgs Empty = new DataSourceJsonDataArgs();

    @Import(name="assumeRoleArn")
    private @Nullable Output<String> assumeRoleArn;

    public Optional<Output<String>> assumeRoleArn() {
        return Optional.ofNullable(this.assumeRoleArn);
    }

    @Import(name="authType")
    private @Nullable Output<String> authType;

    public Optional<Output<String>> authType() {
        return Optional.ofNullable(this.authType);
    }

    @Import(name="authenticationType")
    private @Nullable Output<String> authenticationType;

    public Optional<Output<String>> authenticationType() {
        return Optional.ofNullable(this.authenticationType);
    }

    @Import(name="catalog")
    private @Nullable Output<String> catalog;

    public Optional<Output<String>> catalog() {
        return Optional.ofNullable(this.catalog);
    }

    @Import(name="clientEmail")
    private @Nullable Output<String> clientEmail;

    public Optional<Output<String>> clientEmail() {
        return Optional.ofNullable(this.clientEmail);
    }

    @Import(name="clientId")
    private @Nullable Output<String> clientId;

    public Optional<Output<String>> clientId() {
        return Optional.ofNullable(this.clientId);
    }

    @Import(name="cloudName")
    private @Nullable Output<String> cloudName;

    public Optional<Output<String>> cloudName() {
        return Optional.ofNullable(this.cloudName);
    }

    @Import(name="connMaxLifetime")
    private @Nullable Output<Integer> connMaxLifetime;

    public Optional<Output<Integer>> connMaxLifetime() {
        return Optional.ofNullable(this.connMaxLifetime);
    }

    @Import(name="customMetricsNamespaces")
    private @Nullable Output<String> customMetricsNamespaces;

    public Optional<Output<String>> customMetricsNamespaces() {
        return Optional.ofNullable(this.customMetricsNamespaces);
    }

    @Import(name="database")
    private @Nullable Output<String> database;

    public Optional<Output<String>> database() {
        return Optional.ofNullable(this.database);
    }

    @Import(name="defaultBucket")
    private @Nullable Output<String> defaultBucket;

    public Optional<Output<String>> defaultBucket() {
        return Optional.ofNullable(this.defaultBucket);
    }

    @Import(name="defaultProject")
    private @Nullable Output<String> defaultProject;

    public Optional<Output<String>> defaultProject() {
        return Optional.ofNullable(this.defaultProject);
    }

    @Import(name="defaultRegion")
    private @Nullable Output<String> defaultRegion;

    public Optional<Output<String>> defaultRegion() {
        return Optional.ofNullable(this.defaultRegion);
    }

    @Import(name="derivedFields")
    private @Nullable Output<List<DataSourceJsonDataDerivedFieldArgs>> derivedFields;

    public Optional<Output<List<DataSourceJsonDataDerivedFieldArgs>>> derivedFields() {
        return Optional.ofNullable(this.derivedFields);
    }

    @Import(name="encrypt")
    private @Nullable Output<String> encrypt;

    public Optional<Output<String>> encrypt() {
        return Optional.ofNullable(this.encrypt);
    }

    @Import(name="esVersion")
    private @Nullable Output<String> esVersion;

    public Optional<Output<String>> esVersion() {
        return Optional.ofNullable(this.esVersion);
    }

    @Import(name="externalId")
    private @Nullable Output<String> externalId;

    public Optional<Output<String>> externalId() {
        return Optional.ofNullable(this.externalId);
    }

    @Import(name="githubUrl")
    private @Nullable Output<String> githubUrl;

    public Optional<Output<String>> githubUrl() {
        return Optional.ofNullable(this.githubUrl);
    }

    @Import(name="graphiteVersion")
    private @Nullable Output<String> graphiteVersion;

    public Optional<Output<String>> graphiteVersion() {
        return Optional.ofNullable(this.graphiteVersion);
    }

    @Import(name="httpMethod")
    private @Nullable Output<String> httpMethod;

    public Optional<Output<String>> httpMethod() {
        return Optional.ofNullable(this.httpMethod);
    }

    @Import(name="implementation")
    private @Nullable Output<String> implementation;

    public Optional<Output<String>> implementation() {
        return Optional.ofNullable(this.implementation);
    }

    @Import(name="interval")
    private @Nullable Output<String> interval;

    public Optional<Output<String>> interval() {
        return Optional.ofNullable(this.interval);
    }

    @Import(name="logLevelField")
    private @Nullable Output<String> logLevelField;

    public Optional<Output<String>> logLevelField() {
        return Optional.ofNullable(this.logLevelField);
    }

    @Import(name="logMessageField")
    private @Nullable Output<String> logMessageField;

    public Optional<Output<String>> logMessageField() {
        return Optional.ofNullable(this.logMessageField);
    }

    @Import(name="manageAlerts")
    private @Nullable Output<Boolean> manageAlerts;

    public Optional<Output<Boolean>> manageAlerts() {
        return Optional.ofNullable(this.manageAlerts);
    }

    @Import(name="maxConcurrentShardRequests")
    private @Nullable Output<Integer> maxConcurrentShardRequests;

    public Optional<Output<Integer>> maxConcurrentShardRequests() {
        return Optional.ofNullable(this.maxConcurrentShardRequests);
    }

    @Import(name="maxIdleConns")
    private @Nullable Output<Integer> maxIdleConns;

    public Optional<Output<Integer>> maxIdleConns() {
        return Optional.ofNullable(this.maxIdleConns);
    }

    @Import(name="maxLines")
    private @Nullable Output<Integer> maxLines;

    public Optional<Output<Integer>> maxLines() {
        return Optional.ofNullable(this.maxLines);
    }

    @Import(name="maxOpenConns")
    private @Nullable Output<Integer> maxOpenConns;

    public Optional<Output<Integer>> maxOpenConns() {
        return Optional.ofNullable(this.maxOpenConns);
    }

    @Import(name="orgSlug")
    private @Nullable Output<String> orgSlug;

    public Optional<Output<String>> orgSlug() {
        return Optional.ofNullable(this.orgSlug);
    }

    @Import(name="organization")
    private @Nullable Output<String> organization;

    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    @Import(name="outputLocation")
    private @Nullable Output<String> outputLocation;

    public Optional<Output<String>> outputLocation() {
        return Optional.ofNullable(this.outputLocation);
    }

    @Import(name="postgresVersion")
    private @Nullable Output<Integer> postgresVersion;

    public Optional<Output<Integer>> postgresVersion() {
        return Optional.ofNullable(this.postgresVersion);
    }

    @Import(name="profile")
    private @Nullable Output<String> profile;

    public Optional<Output<String>> profile() {
        return Optional.ofNullable(this.profile);
    }

    @Import(name="queryTimeout")
    private @Nullable Output<String> queryTimeout;

    public Optional<Output<String>> queryTimeout() {
        return Optional.ofNullable(this.queryTimeout);
    }

    @Import(name="sigv4AssumeRoleArn")
    private @Nullable Output<String> sigv4AssumeRoleArn;

    public Optional<Output<String>> sigv4AssumeRoleArn() {
        return Optional.ofNullable(this.sigv4AssumeRoleArn);
    }

    @Import(name="sigv4Auth")
    private @Nullable Output<Boolean> sigv4Auth;

    public Optional<Output<Boolean>> sigv4Auth() {
        return Optional.ofNullable(this.sigv4Auth);
    }

    @Import(name="sigv4AuthType")
    private @Nullable Output<String> sigv4AuthType;

    public Optional<Output<String>> sigv4AuthType() {
        return Optional.ofNullable(this.sigv4AuthType);
    }

    @Import(name="sigv4ExternalId")
    private @Nullable Output<String> sigv4ExternalId;

    public Optional<Output<String>> sigv4ExternalId() {
        return Optional.ofNullable(this.sigv4ExternalId);
    }

    @Import(name="sigv4Profile")
    private @Nullable Output<String> sigv4Profile;

    public Optional<Output<String>> sigv4Profile() {
        return Optional.ofNullable(this.sigv4Profile);
    }

    @Import(name="sigv4Region")
    private @Nullable Output<String> sigv4Region;

    public Optional<Output<String>> sigv4Region() {
        return Optional.ofNullable(this.sigv4Region);
    }

    @Import(name="sslMode")
    private @Nullable Output<String> sslMode;

    public Optional<Output<String>> sslMode() {
        return Optional.ofNullable(this.sslMode);
    }

    @Import(name="subscriptionId")
    private @Nullable Output<String> subscriptionId;

    public Optional<Output<String>> subscriptionId() {
        return Optional.ofNullable(this.subscriptionId);
    }

    @Import(name="tenantId")
    private @Nullable Output<String> tenantId;

    public Optional<Output<String>> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }

    @Import(name="timeField")
    private @Nullable Output<String> timeField;

    public Optional<Output<String>> timeField() {
        return Optional.ofNullable(this.timeField);
    }

    @Import(name="timeInterval")
    private @Nullable Output<String> timeInterval;

    public Optional<Output<String>> timeInterval() {
        return Optional.ofNullable(this.timeInterval);
    }

    @Import(name="timescaledb")
    private @Nullable Output<Boolean> timescaledb;

    public Optional<Output<Boolean>> timescaledb() {
        return Optional.ofNullable(this.timescaledb);
    }

    @Import(name="tlsAuth")
    private @Nullable Output<Boolean> tlsAuth;

    public Optional<Output<Boolean>> tlsAuth() {
        return Optional.ofNullable(this.tlsAuth);
    }

    @Import(name="tlsAuthWithCaCert")
    private @Nullable Output<Boolean> tlsAuthWithCaCert;

    public Optional<Output<Boolean>> tlsAuthWithCaCert() {
        return Optional.ofNullable(this.tlsAuthWithCaCert);
    }

    @Import(name="tlsConfigurationMethod")
    private @Nullable Output<String> tlsConfigurationMethod;

    public Optional<Output<String>> tlsConfigurationMethod() {
        return Optional.ofNullable(this.tlsConfigurationMethod);
    }

    @Import(name="tlsSkipVerify")
    private @Nullable Output<Boolean> tlsSkipVerify;

    public Optional<Output<Boolean>> tlsSkipVerify() {
        return Optional.ofNullable(this.tlsSkipVerify);
    }

    @Import(name="tokenUri")
    private @Nullable Output<String> tokenUri;

    public Optional<Output<String>> tokenUri() {
        return Optional.ofNullable(this.tokenUri);
    }

    @Import(name="tracingDatasourceUid")
    private @Nullable Output<String> tracingDatasourceUid;

    public Optional<Output<String>> tracingDatasourceUid() {
        return Optional.ofNullable(this.tracingDatasourceUid);
    }

    @Import(name="tsdbResolution")
    private @Nullable Output<Integer> tsdbResolution;

    public Optional<Output<Integer>> tsdbResolution() {
        return Optional.ofNullable(this.tsdbResolution);
    }

    @Import(name="tsdbVersion")
    private @Nullable Output<Integer> tsdbVersion;

    public Optional<Output<Integer>> tsdbVersion() {
        return Optional.ofNullable(this.tsdbVersion);
    }

    @Import(name="version")
    private @Nullable Output<String> version;

    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    @Import(name="workgroup")
    private @Nullable Output<String> workgroup;

    public Optional<Output<String>> workgroup() {
        return Optional.ofNullable(this.workgroup);
    }

    @Import(name="xpackEnabled")
    private @Nullable Output<Boolean> xpackEnabled;

    public Optional<Output<Boolean>> xpackEnabled() {
        return Optional.ofNullable(this.xpackEnabled);
    }

    private DataSourceJsonDataArgs() {}

    private DataSourceJsonDataArgs(DataSourceJsonDataArgs $) {
        this.assumeRoleArn = $.assumeRoleArn;
        this.authType = $.authType;
        this.authenticationType = $.authenticationType;
        this.catalog = $.catalog;
        this.clientEmail = $.clientEmail;
        this.clientId = $.clientId;
        this.cloudName = $.cloudName;
        this.connMaxLifetime = $.connMaxLifetime;
        this.customMetricsNamespaces = $.customMetricsNamespaces;
        this.database = $.database;
        this.defaultBucket = $.defaultBucket;
        this.defaultProject = $.defaultProject;
        this.defaultRegion = $.defaultRegion;
        this.derivedFields = $.derivedFields;
        this.encrypt = $.encrypt;
        this.esVersion = $.esVersion;
        this.externalId = $.externalId;
        this.githubUrl = $.githubUrl;
        this.graphiteVersion = $.graphiteVersion;
        this.httpMethod = $.httpMethod;
        this.implementation = $.implementation;
        this.interval = $.interval;
        this.logLevelField = $.logLevelField;
        this.logMessageField = $.logMessageField;
        this.manageAlerts = $.manageAlerts;
        this.maxConcurrentShardRequests = $.maxConcurrentShardRequests;
        this.maxIdleConns = $.maxIdleConns;
        this.maxLines = $.maxLines;
        this.maxOpenConns = $.maxOpenConns;
        this.orgSlug = $.orgSlug;
        this.organization = $.organization;
        this.outputLocation = $.outputLocation;
        this.postgresVersion = $.postgresVersion;
        this.profile = $.profile;
        this.queryTimeout = $.queryTimeout;
        this.sigv4AssumeRoleArn = $.sigv4AssumeRoleArn;
        this.sigv4Auth = $.sigv4Auth;
        this.sigv4AuthType = $.sigv4AuthType;
        this.sigv4ExternalId = $.sigv4ExternalId;
        this.sigv4Profile = $.sigv4Profile;
        this.sigv4Region = $.sigv4Region;
        this.sslMode = $.sslMode;
        this.subscriptionId = $.subscriptionId;
        this.tenantId = $.tenantId;
        this.timeField = $.timeField;
        this.timeInterval = $.timeInterval;
        this.timescaledb = $.timescaledb;
        this.tlsAuth = $.tlsAuth;
        this.tlsAuthWithCaCert = $.tlsAuthWithCaCert;
        this.tlsConfigurationMethod = $.tlsConfigurationMethod;
        this.tlsSkipVerify = $.tlsSkipVerify;
        this.tokenUri = $.tokenUri;
        this.tracingDatasourceUid = $.tracingDatasourceUid;
        this.tsdbResolution = $.tsdbResolution;
        this.tsdbVersion = $.tsdbVersion;
        this.version = $.version;
        this.workgroup = $.workgroup;
        this.xpackEnabled = $.xpackEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataSourceJsonDataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataSourceJsonDataArgs $;

        public Builder() {
            $ = new DataSourceJsonDataArgs();
        }

        public Builder(DataSourceJsonDataArgs defaults) {
            $ = new DataSourceJsonDataArgs(Objects.requireNonNull(defaults));
        }

        public Builder assumeRoleArn(@Nullable Output<String> assumeRoleArn) {
            $.assumeRoleArn = assumeRoleArn;
            return this;
        }

        public Builder assumeRoleArn(String assumeRoleArn) {
            return assumeRoleArn(Output.of(assumeRoleArn));
        }

        public Builder authType(@Nullable Output<String> authType) {
            $.authType = authType;
            return this;
        }

        public Builder authType(String authType) {
            return authType(Output.of(authType));
        }

        public Builder authenticationType(@Nullable Output<String> authenticationType) {
            $.authenticationType = authenticationType;
            return this;
        }

        public Builder authenticationType(String authenticationType) {
            return authenticationType(Output.of(authenticationType));
        }

        public Builder catalog(@Nullable Output<String> catalog) {
            $.catalog = catalog;
            return this;
        }

        public Builder catalog(String catalog) {
            return catalog(Output.of(catalog));
        }

        public Builder clientEmail(@Nullable Output<String> clientEmail) {
            $.clientEmail = clientEmail;
            return this;
        }

        public Builder clientEmail(String clientEmail) {
            return clientEmail(Output.of(clientEmail));
        }

        public Builder clientId(@Nullable Output<String> clientId) {
            $.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            return clientId(Output.of(clientId));
        }

        public Builder cloudName(@Nullable Output<String> cloudName) {
            $.cloudName = cloudName;
            return this;
        }

        public Builder cloudName(String cloudName) {
            return cloudName(Output.of(cloudName));
        }

        public Builder connMaxLifetime(@Nullable Output<Integer> connMaxLifetime) {
            $.connMaxLifetime = connMaxLifetime;
            return this;
        }

        public Builder connMaxLifetime(Integer connMaxLifetime) {
            return connMaxLifetime(Output.of(connMaxLifetime));
        }

        public Builder customMetricsNamespaces(@Nullable Output<String> customMetricsNamespaces) {
            $.customMetricsNamespaces = customMetricsNamespaces;
            return this;
        }

        public Builder customMetricsNamespaces(String customMetricsNamespaces) {
            return customMetricsNamespaces(Output.of(customMetricsNamespaces));
        }

        public Builder database(@Nullable Output<String> database) {
            $.database = database;
            return this;
        }

        public Builder database(String database) {
            return database(Output.of(database));
        }

        public Builder defaultBucket(@Nullable Output<String> defaultBucket) {
            $.defaultBucket = defaultBucket;
            return this;
        }

        public Builder defaultBucket(String defaultBucket) {
            return defaultBucket(Output.of(defaultBucket));
        }

        public Builder defaultProject(@Nullable Output<String> defaultProject) {
            $.defaultProject = defaultProject;
            return this;
        }

        public Builder defaultProject(String defaultProject) {
            return defaultProject(Output.of(defaultProject));
        }

        public Builder defaultRegion(@Nullable Output<String> defaultRegion) {
            $.defaultRegion = defaultRegion;
            return this;
        }

        public Builder defaultRegion(String defaultRegion) {
            return defaultRegion(Output.of(defaultRegion));
        }

        public Builder derivedFields(@Nullable Output<List<DataSourceJsonDataDerivedFieldArgs>> derivedFields) {
            $.derivedFields = derivedFields;
            return this;
        }

        public Builder derivedFields(List<DataSourceJsonDataDerivedFieldArgs> derivedFields) {
            return derivedFields(Output.of(derivedFields));
        }

        public Builder derivedFields(DataSourceJsonDataDerivedFieldArgs... derivedFields) {
            return derivedFields(List.of(derivedFields));
        }

        public Builder encrypt(@Nullable Output<String> encrypt) {
            $.encrypt = encrypt;
            return this;
        }

        public Builder encrypt(String encrypt) {
            return encrypt(Output.of(encrypt));
        }

        public Builder esVersion(@Nullable Output<String> esVersion) {
            $.esVersion = esVersion;
            return this;
        }

        public Builder esVersion(String esVersion) {
            return esVersion(Output.of(esVersion));
        }

        public Builder externalId(@Nullable Output<String> externalId) {
            $.externalId = externalId;
            return this;
        }

        public Builder externalId(String externalId) {
            return externalId(Output.of(externalId));
        }

        public Builder githubUrl(@Nullable Output<String> githubUrl) {
            $.githubUrl = githubUrl;
            return this;
        }

        public Builder githubUrl(String githubUrl) {
            return githubUrl(Output.of(githubUrl));
        }

        public Builder graphiteVersion(@Nullable Output<String> graphiteVersion) {
            $.graphiteVersion = graphiteVersion;
            return this;
        }

        public Builder graphiteVersion(String graphiteVersion) {
            return graphiteVersion(Output.of(graphiteVersion));
        }

        public Builder httpMethod(@Nullable Output<String> httpMethod) {
            $.httpMethod = httpMethod;
            return this;
        }

        public Builder httpMethod(String httpMethod) {
            return httpMethod(Output.of(httpMethod));
        }

        public Builder implementation(@Nullable Output<String> implementation) {
            $.implementation = implementation;
            return this;
        }

        public Builder implementation(String implementation) {
            return implementation(Output.of(implementation));
        }

        public Builder interval(@Nullable Output<String> interval) {
            $.interval = interval;
            return this;
        }

        public Builder interval(String interval) {
            return interval(Output.of(interval));
        }

        public Builder logLevelField(@Nullable Output<String> logLevelField) {
            $.logLevelField = logLevelField;
            return this;
        }

        public Builder logLevelField(String logLevelField) {
            return logLevelField(Output.of(logLevelField));
        }

        public Builder logMessageField(@Nullable Output<String> logMessageField) {
            $.logMessageField = logMessageField;
            return this;
        }

        public Builder logMessageField(String logMessageField) {
            return logMessageField(Output.of(logMessageField));
        }

        public Builder manageAlerts(@Nullable Output<Boolean> manageAlerts) {
            $.manageAlerts = manageAlerts;
            return this;
        }

        public Builder manageAlerts(Boolean manageAlerts) {
            return manageAlerts(Output.of(manageAlerts));
        }

        public Builder maxConcurrentShardRequests(@Nullable Output<Integer> maxConcurrentShardRequests) {
            $.maxConcurrentShardRequests = maxConcurrentShardRequests;
            return this;
        }

        public Builder maxConcurrentShardRequests(Integer maxConcurrentShardRequests) {
            return maxConcurrentShardRequests(Output.of(maxConcurrentShardRequests));
        }

        public Builder maxIdleConns(@Nullable Output<Integer> maxIdleConns) {
            $.maxIdleConns = maxIdleConns;
            return this;
        }

        public Builder maxIdleConns(Integer maxIdleConns) {
            return maxIdleConns(Output.of(maxIdleConns));
        }

        public Builder maxLines(@Nullable Output<Integer> maxLines) {
            $.maxLines = maxLines;
            return this;
        }

        public Builder maxLines(Integer maxLines) {
            return maxLines(Output.of(maxLines));
        }

        public Builder maxOpenConns(@Nullable Output<Integer> maxOpenConns) {
            $.maxOpenConns = maxOpenConns;
            return this;
        }

        public Builder maxOpenConns(Integer maxOpenConns) {
            return maxOpenConns(Output.of(maxOpenConns));
        }

        public Builder orgSlug(@Nullable Output<String> orgSlug) {
            $.orgSlug = orgSlug;
            return this;
        }

        public Builder orgSlug(String orgSlug) {
            return orgSlug(Output.of(orgSlug));
        }

        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        public Builder outputLocation(@Nullable Output<String> outputLocation) {
            $.outputLocation = outputLocation;
            return this;
        }

        public Builder outputLocation(String outputLocation) {
            return outputLocation(Output.of(outputLocation));
        }

        public Builder postgresVersion(@Nullable Output<Integer> postgresVersion) {
            $.postgresVersion = postgresVersion;
            return this;
        }

        public Builder postgresVersion(Integer postgresVersion) {
            return postgresVersion(Output.of(postgresVersion));
        }

        public Builder profile(@Nullable Output<String> profile) {
            $.profile = profile;
            return this;
        }

        public Builder profile(String profile) {
            return profile(Output.of(profile));
        }

        public Builder queryTimeout(@Nullable Output<String> queryTimeout) {
            $.queryTimeout = queryTimeout;
            return this;
        }

        public Builder queryTimeout(String queryTimeout) {
            return queryTimeout(Output.of(queryTimeout));
        }

        public Builder sigv4AssumeRoleArn(@Nullable Output<String> sigv4AssumeRoleArn) {
            $.sigv4AssumeRoleArn = sigv4AssumeRoleArn;
            return this;
        }

        public Builder sigv4AssumeRoleArn(String sigv4AssumeRoleArn) {
            return sigv4AssumeRoleArn(Output.of(sigv4AssumeRoleArn));
        }

        public Builder sigv4Auth(@Nullable Output<Boolean> sigv4Auth) {
            $.sigv4Auth = sigv4Auth;
            return this;
        }

        public Builder sigv4Auth(Boolean sigv4Auth) {
            return sigv4Auth(Output.of(sigv4Auth));
        }

        public Builder sigv4AuthType(@Nullable Output<String> sigv4AuthType) {
            $.sigv4AuthType = sigv4AuthType;
            return this;
        }

        public Builder sigv4AuthType(String sigv4AuthType) {
            return sigv4AuthType(Output.of(sigv4AuthType));
        }

        public Builder sigv4ExternalId(@Nullable Output<String> sigv4ExternalId) {
            $.sigv4ExternalId = sigv4ExternalId;
            return this;
        }

        public Builder sigv4ExternalId(String sigv4ExternalId) {
            return sigv4ExternalId(Output.of(sigv4ExternalId));
        }

        public Builder sigv4Profile(@Nullable Output<String> sigv4Profile) {
            $.sigv4Profile = sigv4Profile;
            return this;
        }

        public Builder sigv4Profile(String sigv4Profile) {
            return sigv4Profile(Output.of(sigv4Profile));
        }

        public Builder sigv4Region(@Nullable Output<String> sigv4Region) {
            $.sigv4Region = sigv4Region;
            return this;
        }

        public Builder sigv4Region(String sigv4Region) {
            return sigv4Region(Output.of(sigv4Region));
        }

        public Builder sslMode(@Nullable Output<String> sslMode) {
            $.sslMode = sslMode;
            return this;
        }

        public Builder sslMode(String sslMode) {
            return sslMode(Output.of(sslMode));
        }

        public Builder subscriptionId(@Nullable Output<String> subscriptionId) {
            $.subscriptionId = subscriptionId;
            return this;
        }

        public Builder subscriptionId(String subscriptionId) {
            return subscriptionId(Output.of(subscriptionId));
        }

        public Builder tenantId(@Nullable Output<String> tenantId) {
            $.tenantId = tenantId;
            return this;
        }

        public Builder tenantId(String tenantId) {
            return tenantId(Output.of(tenantId));
        }

        public Builder timeField(@Nullable Output<String> timeField) {
            $.timeField = timeField;
            return this;
        }

        public Builder timeField(String timeField) {
            return timeField(Output.of(timeField));
        }

        public Builder timeInterval(@Nullable Output<String> timeInterval) {
            $.timeInterval = timeInterval;
            return this;
        }

        public Builder timeInterval(String timeInterval) {
            return timeInterval(Output.of(timeInterval));
        }

        public Builder timescaledb(@Nullable Output<Boolean> timescaledb) {
            $.timescaledb = timescaledb;
            return this;
        }

        public Builder timescaledb(Boolean timescaledb) {
            return timescaledb(Output.of(timescaledb));
        }

        public Builder tlsAuth(@Nullable Output<Boolean> tlsAuth) {
            $.tlsAuth = tlsAuth;
            return this;
        }

        public Builder tlsAuth(Boolean tlsAuth) {
            return tlsAuth(Output.of(tlsAuth));
        }

        public Builder tlsAuthWithCaCert(@Nullable Output<Boolean> tlsAuthWithCaCert) {
            $.tlsAuthWithCaCert = tlsAuthWithCaCert;
            return this;
        }

        public Builder tlsAuthWithCaCert(Boolean tlsAuthWithCaCert) {
            return tlsAuthWithCaCert(Output.of(tlsAuthWithCaCert));
        }

        public Builder tlsConfigurationMethod(@Nullable Output<String> tlsConfigurationMethod) {
            $.tlsConfigurationMethod = tlsConfigurationMethod;
            return this;
        }

        public Builder tlsConfigurationMethod(String tlsConfigurationMethod) {
            return tlsConfigurationMethod(Output.of(tlsConfigurationMethod));
        }

        public Builder tlsSkipVerify(@Nullable Output<Boolean> tlsSkipVerify) {
            $.tlsSkipVerify = tlsSkipVerify;
            return this;
        }

        public Builder tlsSkipVerify(Boolean tlsSkipVerify) {
            return tlsSkipVerify(Output.of(tlsSkipVerify));
        }

        public Builder tokenUri(@Nullable Output<String> tokenUri) {
            $.tokenUri = tokenUri;
            return this;
        }

        public Builder tokenUri(String tokenUri) {
            return tokenUri(Output.of(tokenUri));
        }

        public Builder tracingDatasourceUid(@Nullable Output<String> tracingDatasourceUid) {
            $.tracingDatasourceUid = tracingDatasourceUid;
            return this;
        }

        public Builder tracingDatasourceUid(String tracingDatasourceUid) {
            return tracingDatasourceUid(Output.of(tracingDatasourceUid));
        }

        public Builder tsdbResolution(@Nullable Output<Integer> tsdbResolution) {
            $.tsdbResolution = tsdbResolution;
            return this;
        }

        public Builder tsdbResolution(Integer tsdbResolution) {
            return tsdbResolution(Output.of(tsdbResolution));
        }

        public Builder tsdbVersion(@Nullable Output<Integer> tsdbVersion) {
            $.tsdbVersion = tsdbVersion;
            return this;
        }

        public Builder tsdbVersion(Integer tsdbVersion) {
            return tsdbVersion(Output.of(tsdbVersion));
        }

        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        public Builder version(String version) {
            return version(Output.of(version));
        }

        public Builder workgroup(@Nullable Output<String> workgroup) {
            $.workgroup = workgroup;
            return this;
        }

        public Builder workgroup(String workgroup) {
            return workgroup(Output.of(workgroup));
        }

        public Builder xpackEnabled(@Nullable Output<Boolean> xpackEnabled) {
            $.xpackEnabled = xpackEnabled;
            return this;
        }

        public Builder xpackEnabled(Boolean xpackEnabled) {
            return xpackEnabled(Output.of(xpackEnabled));
        }

        public DataSourceJsonDataArgs build() {
            return $;
        }
    }

}
