// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DataSourceSecureJsonDataArgs extends com.pulumi.resources.ResourceArgs {

    public static final DataSourceSecureJsonDataArgs Empty = new DataSourceSecureJsonDataArgs();

    @Import(name="accessKey")
    private @Nullable Output<String> accessKey;

    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    @Import(name="accessToken")
    private @Nullable Output<String> accessToken;

    public Optional<Output<String>> accessToken() {
        return Optional.ofNullable(this.accessToken);
    }

    @Import(name="authToken")
    private @Nullable Output<String> authToken;

    public Optional<Output<String>> authToken() {
        return Optional.ofNullable(this.authToken);
    }

    @Import(name="basicAuthPassword")
    private @Nullable Output<String> basicAuthPassword;

    public Optional<Output<String>> basicAuthPassword() {
        return Optional.ofNullable(this.basicAuthPassword);
    }

    @Import(name="clientSecret")
    private @Nullable Output<String> clientSecret;

    public Optional<Output<String>> clientSecret() {
        return Optional.ofNullable(this.clientSecret);
    }

    @Import(name="password")
    private @Nullable Output<String> password;

    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    @Import(name="privateKey")
    private @Nullable Output<String> privateKey;

    public Optional<Output<String>> privateKey() {
        return Optional.ofNullable(this.privateKey);
    }

    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    @Import(name="sigv4AccessKey")
    private @Nullable Output<String> sigv4AccessKey;

    public Optional<Output<String>> sigv4AccessKey() {
        return Optional.ofNullable(this.sigv4AccessKey);
    }

    @Import(name="sigv4SecretKey")
    private @Nullable Output<String> sigv4SecretKey;

    public Optional<Output<String>> sigv4SecretKey() {
        return Optional.ofNullable(this.sigv4SecretKey);
    }

    @Import(name="tlsCaCert")
    private @Nullable Output<String> tlsCaCert;

    public Optional<Output<String>> tlsCaCert() {
        return Optional.ofNullable(this.tlsCaCert);
    }

    @Import(name="tlsClientCert")
    private @Nullable Output<String> tlsClientCert;

    public Optional<Output<String>> tlsClientCert() {
        return Optional.ofNullable(this.tlsClientCert);
    }

    @Import(name="tlsClientKey")
    private @Nullable Output<String> tlsClientKey;

    public Optional<Output<String>> tlsClientKey() {
        return Optional.ofNullable(this.tlsClientKey);
    }

    private DataSourceSecureJsonDataArgs() {}

    private DataSourceSecureJsonDataArgs(DataSourceSecureJsonDataArgs $) {
        this.accessKey = $.accessKey;
        this.accessToken = $.accessToken;
        this.authToken = $.authToken;
        this.basicAuthPassword = $.basicAuthPassword;
        this.clientSecret = $.clientSecret;
        this.password = $.password;
        this.privateKey = $.privateKey;
        this.secretKey = $.secretKey;
        this.sigv4AccessKey = $.sigv4AccessKey;
        this.sigv4SecretKey = $.sigv4SecretKey;
        this.tlsCaCert = $.tlsCaCert;
        this.tlsClientCert = $.tlsClientCert;
        this.tlsClientKey = $.tlsClientKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataSourceSecureJsonDataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataSourceSecureJsonDataArgs $;

        public Builder() {
            $ = new DataSourceSecureJsonDataArgs();
        }

        public Builder(DataSourceSecureJsonDataArgs defaults) {
            $ = new DataSourceSecureJsonDataArgs(Objects.requireNonNull(defaults));
        }

        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        public Builder accessToken(@Nullable Output<String> accessToken) {
            $.accessToken = accessToken;
            return this;
        }

        public Builder accessToken(String accessToken) {
            return accessToken(Output.of(accessToken));
        }

        public Builder authToken(@Nullable Output<String> authToken) {
            $.authToken = authToken;
            return this;
        }

        public Builder authToken(String authToken) {
            return authToken(Output.of(authToken));
        }

        public Builder basicAuthPassword(@Nullable Output<String> basicAuthPassword) {
            $.basicAuthPassword = basicAuthPassword;
            return this;
        }

        public Builder basicAuthPassword(String basicAuthPassword) {
            return basicAuthPassword(Output.of(basicAuthPassword));
        }

        public Builder clientSecret(@Nullable Output<String> clientSecret) {
            $.clientSecret = clientSecret;
            return this;
        }

        public Builder clientSecret(String clientSecret) {
            return clientSecret(Output.of(clientSecret));
        }

        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        public Builder password(String password) {
            return password(Output.of(password));
        }

        public Builder privateKey(@Nullable Output<String> privateKey) {
            $.privateKey = privateKey;
            return this;
        }

        public Builder privateKey(String privateKey) {
            return privateKey(Output.of(privateKey));
        }

        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        public Builder sigv4AccessKey(@Nullable Output<String> sigv4AccessKey) {
            $.sigv4AccessKey = sigv4AccessKey;
            return this;
        }

        public Builder sigv4AccessKey(String sigv4AccessKey) {
            return sigv4AccessKey(Output.of(sigv4AccessKey));
        }

        public Builder sigv4SecretKey(@Nullable Output<String> sigv4SecretKey) {
            $.sigv4SecretKey = sigv4SecretKey;
            return this;
        }

        public Builder sigv4SecretKey(String sigv4SecretKey) {
            return sigv4SecretKey(Output.of(sigv4SecretKey));
        }

        public Builder tlsCaCert(@Nullable Output<String> tlsCaCert) {
            $.tlsCaCert = tlsCaCert;
            return this;
        }

        public Builder tlsCaCert(String tlsCaCert) {
            return tlsCaCert(Output.of(tlsCaCert));
        }

        public Builder tlsClientCert(@Nullable Output<String> tlsClientCert) {
            $.tlsClientCert = tlsClientCert;
            return this;
        }

        public Builder tlsClientCert(String tlsClientCert) {
            return tlsClientCert(Output.of(tlsClientCert));
        }

        public Builder tlsClientKey(@Nullable Output<String> tlsClientKey) {
            $.tlsClientKey = tlsClientKey;
            return this;
        }

        public Builder tlsClientKey(String tlsClientKey) {
            return tlsClientKey(Output.of(tlsClientKey));
        }

        public DataSourceSecureJsonDataArgs build() {
            return $;
        }
    }

}
