// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDashboardsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDashboardsPlainArgs Empty = new GetDashboardsPlainArgs();

    @Import(name="folderIds")
    private @Nullable List<Integer> folderIds;

    public Optional<List<Integer>> folderIds() {
        return Optional.ofNullable(this.folderIds);
    }

    @Import(name="limit")
    private @Nullable Integer limit;

    public Optional<Integer> limit() {
        return Optional.ofNullable(this.limit);
    }

    @Import(name="tags")
    private @Nullable List<String> tags;

    public Optional<List<String>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private GetDashboardsPlainArgs() {}

    private GetDashboardsPlainArgs(GetDashboardsPlainArgs $) {
        this.folderIds = $.folderIds;
        this.limit = $.limit;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDashboardsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDashboardsPlainArgs $;

        public Builder() {
            $ = new GetDashboardsPlainArgs();
        }

        public Builder(GetDashboardsPlainArgs defaults) {
            $ = new GetDashboardsPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder folderIds(@Nullable List<Integer> folderIds) {
            $.folderIds = folderIds;
            return this;
        }

        public Builder folderIds(Integer... folderIds) {
            return folderIds(List.of(folderIds));
        }

        public Builder limit(@Nullable Integer limit) {
            $.limit = limit;
            return this;
        }

        public Builder tags(@Nullable List<String> tags) {
            $.tags = tags;
            return this;
        }

        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }

        public GetDashboardsPlainArgs build() {
            return $;
        }
    }

}
