// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetLibraryPanelPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetLibraryPanelPlainArgs Empty = new GetLibraryPanelPlainArgs();

    @Import(name="name")
    private @Nullable String name;

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="uid")
    private @Nullable String uid;

    public Optional<String> uid() {
        return Optional.ofNullable(this.uid);
    }

    private GetLibraryPanelPlainArgs() {}

    private GetLibraryPanelPlainArgs(GetLibraryPanelPlainArgs $) {
        this.name = $.name;
        this.uid = $.uid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetLibraryPanelPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetLibraryPanelPlainArgs $;

        public Builder() {
            $ = new GetLibraryPanelPlainArgs();
        }

        public Builder(GetLibraryPanelPlainArgs defaults) {
            $ = new GetLibraryPanelPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public Builder uid(@Nullable String uid) {
            $.uid = uid;
            return this;
        }

        public GetLibraryPanelPlainArgs build() {
            return $;
        }
    }

}
