// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetUserPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetUserPlainArgs Empty = new GetUserPlainArgs();

    @Import(name="email")
    private @Nullable String email;

    public Optional<String> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="login")
    private @Nullable String login;

    public Optional<String> login() {
        return Optional.ofNullable(this.login);
    }

    @Import(name="userId")
    private @Nullable Integer userId;

    public Optional<Integer> userId() {
        return Optional.ofNullable(this.userId);
    }

    private GetUserPlainArgs() {}

    private GetUserPlainArgs(GetUserPlainArgs $) {
        this.email = $.email;
        this.login = $.login;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetUserPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetUserPlainArgs $;

        public Builder() {
            $ = new GetUserPlainArgs();
        }

        public Builder(GetUserPlainArgs defaults) {
            $ = new GetUserPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder email(@Nullable String email) {
            $.email = email;
            return this;
        }

        public Builder login(@Nullable String login) {
            $.login = login;
            return this;
        }

        public Builder userId(@Nullable Integer userId) {
            $.userId = userId;
            return this;
        }

        public GetUserPlainArgs build() {
            return $;
        }
    }

}
