// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class OncallIntegrationDefaultRouteSlackArgs extends com.pulumi.resources.ResourceArgs {

    public static final OncallIntegrationDefaultRouteSlackArgs Empty = new OncallIntegrationDefaultRouteSlackArgs();

    @Import(name="channelId", required=true)
    private Output<String> channelId;

    public Output<String> channelId() {
        return this.channelId;
    }

    private OncallIntegrationDefaultRouteSlackArgs() {}

    private OncallIntegrationDefaultRouteSlackArgs(OncallIntegrationDefaultRouteSlackArgs $) {
        this.channelId = $.channelId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OncallIntegrationDefaultRouteSlackArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OncallIntegrationDefaultRouteSlackArgs $;

        public Builder() {
            $ = new OncallIntegrationDefaultRouteSlackArgs();
        }

        public Builder(OncallIntegrationDefaultRouteSlackArgs defaults) {
            $ = new OncallIntegrationDefaultRouteSlackArgs(Objects.requireNonNull(defaults));
        }

        public Builder channelId(Output<String> channelId) {
            $.channelId = channelId;
            return this;
        }

        public Builder channelId(String channelId) {
            return channelId(Output.of(channelId));
        }

        public OncallIntegrationDefaultRouteSlackArgs build() {
            $.channelId = Objects.requireNonNull($.channelId, "expected parameter 'channelId' to be non-null");
            return $;
        }
    }

}
