// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.grafana.inputs.OncallIntegrationDefaultRouteSlackArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OncallIntegrationDefaultRouteArgs extends com.pulumi.resources.ResourceArgs {

    public static final OncallIntegrationDefaultRouteArgs Empty = new OncallIntegrationDefaultRouteArgs();

    @Import(name="escalationChainId")
    private @Nullable Output<String> escalationChainId;

    public Optional<Output<String>> escalationChainId() {
        return Optional.ofNullable(this.escalationChainId);
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="slack")
    private @Nullable Output<OncallIntegrationDefaultRouteSlackArgs> slack;

    public Optional<Output<OncallIntegrationDefaultRouteSlackArgs>> slack() {
        return Optional.ofNullable(this.slack);
    }

    private OncallIntegrationDefaultRouteArgs() {}

    private OncallIntegrationDefaultRouteArgs(OncallIntegrationDefaultRouteArgs $) {
        this.escalationChainId = $.escalationChainId;
        this.id = $.id;
        this.slack = $.slack;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OncallIntegrationDefaultRouteArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OncallIntegrationDefaultRouteArgs $;

        public Builder() {
            $ = new OncallIntegrationDefaultRouteArgs();
        }

        public Builder(OncallIntegrationDefaultRouteArgs defaults) {
            $ = new OncallIntegrationDefaultRouteArgs(Objects.requireNonNull(defaults));
        }

        public Builder escalationChainId(@Nullable Output<String> escalationChainId) {
            $.escalationChainId = escalationChainId;
            return this;
        }

        public Builder escalationChainId(String escalationChainId) {
            return escalationChainId(Output.of(escalationChainId));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public Builder slack(@Nullable Output<OncallIntegrationDefaultRouteSlackArgs> slack) {
            $.slack = slack;
            return this;
        }

        public Builder slack(OncallIntegrationDefaultRouteSlackArgs slack) {
            return slack(Output.of(slack));
        }

        public OncallIntegrationDefaultRouteArgs build() {
            return $;
        }
    }

}
