// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.grafana.inputs.RuleGroupRuleDataArgs;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RuleGroupRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final RuleGroupRuleArgs Empty = new RuleGroupRuleArgs();

    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    @Import(name="condition", required=true)
    private Output<String> condition;

    public Output<String> condition() {
        return this.condition;
    }

    @Import(name="datas", required=true)
    private Output<List<RuleGroupRuleDataArgs>> datas;

    public Output<List<RuleGroupRuleDataArgs>> datas() {
        return this.datas;
    }

    @Import(name="execErrState")
    private @Nullable Output<String> execErrState;

    public Optional<Output<String>> execErrState() {
        return Optional.ofNullable(this.execErrState);
    }

    @Import(name="for")
    private @Nullable Output<String> for_;

    public Optional<Output<String>> for_() {
        return Optional.ofNullable(this.for_);
    }

    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="noDataState")
    private @Nullable Output<String> noDataState;

    public Optional<Output<String>> noDataState() {
        return Optional.ofNullable(this.noDataState);
    }

    @Import(name="uid")
    private @Nullable Output<String> uid;

    public Optional<Output<String>> uid() {
        return Optional.ofNullable(this.uid);
    }

    private RuleGroupRuleArgs() {}

    private RuleGroupRuleArgs(RuleGroupRuleArgs $) {
        this.annotations = $.annotations;
        this.condition = $.condition;
        this.datas = $.datas;
        this.execErrState = $.execErrState;
        this.for_ = $.for_;
        this.labels = $.labels;
        this.name = $.name;
        this.noDataState = $.noDataState;
        this.uid = $.uid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RuleGroupRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RuleGroupRuleArgs $;

        public Builder() {
            $ = new RuleGroupRuleArgs();
        }

        public Builder(RuleGroupRuleArgs defaults) {
            $ = new RuleGroupRuleArgs(Objects.requireNonNull(defaults));
        }

        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        public Builder condition(Output<String> condition) {
            $.condition = condition;
            return this;
        }

        public Builder condition(String condition) {
            return condition(Output.of(condition));
        }

        public Builder datas(Output<List<RuleGroupRuleDataArgs>> datas) {
            $.datas = datas;
            return this;
        }

        public Builder datas(List<RuleGroupRuleDataArgs> datas) {
            return datas(Output.of(datas));
        }

        public Builder datas(RuleGroupRuleDataArgs... datas) {
            return datas(List.of(datas));
        }

        public Builder execErrState(@Nullable Output<String> execErrState) {
            $.execErrState = execErrState;
            return this;
        }

        public Builder execErrState(String execErrState) {
            return execErrState(Output.of(execErrState));
        }

        public Builder for_(@Nullable Output<String> for_) {
            $.for_ = for_;
            return this;
        }

        public Builder for_(String for_) {
            return for_(Output.of(for_));
        }

        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder noDataState(@Nullable Output<String> noDataState) {
            $.noDataState = noDataState;
            return this;
        }

        public Builder noDataState(String noDataState) {
            return noDataState(Output.of(noDataState));
        }

        public Builder uid(@Nullable Output<String> uid) {
            $.uid = uid;
            return this;
        }

        public Builder uid(String uid) {
            return uid(Output.of(uid));
        }

        public RuleGroupRuleArgs build() {
            $.condition = Objects.requireNonNull($.condition, "expected parameter 'condition' to be non-null");
            $.datas = Objects.requireNonNull($.datas, "expected parameter 'datas' to be non-null");
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
