// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.grafana.inputs.SyntheticMonitoringCheckSettingsDnsArgs;
import com.pulumi.grafana.inputs.SyntheticMonitoringCheckSettingsHttpArgs;
import com.pulumi.grafana.inputs.SyntheticMonitoringCheckSettingsPingArgs;
import com.pulumi.grafana.inputs.SyntheticMonitoringCheckSettingsTcpArgs;
import com.pulumi.grafana.inputs.SyntheticMonitoringCheckSettingsTracerouteArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SyntheticMonitoringCheckSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final SyntheticMonitoringCheckSettingsArgs Empty = new SyntheticMonitoringCheckSettingsArgs();

    @Import(name="dns")
    private @Nullable Output<SyntheticMonitoringCheckSettingsDnsArgs> dns;

    public Optional<Output<SyntheticMonitoringCheckSettingsDnsArgs>> dns() {
        return Optional.ofNullable(this.dns);
    }

    @Import(name="http")
    private @Nullable Output<SyntheticMonitoringCheckSettingsHttpArgs> http;

    public Optional<Output<SyntheticMonitoringCheckSettingsHttpArgs>> http() {
        return Optional.ofNullable(this.http);
    }

    @Import(name="ping")
    private @Nullable Output<SyntheticMonitoringCheckSettingsPingArgs> ping;

    public Optional<Output<SyntheticMonitoringCheckSettingsPingArgs>> ping() {
        return Optional.ofNullable(this.ping);
    }

    @Import(name="tcp")
    private @Nullable Output<SyntheticMonitoringCheckSettingsTcpArgs> tcp;

    public Optional<Output<SyntheticMonitoringCheckSettingsTcpArgs>> tcp() {
        return Optional.ofNullable(this.tcp);
    }

    @Import(name="traceroute")
    private @Nullable Output<SyntheticMonitoringCheckSettingsTracerouteArgs> traceroute;

    public Optional<Output<SyntheticMonitoringCheckSettingsTracerouteArgs>> traceroute() {
        return Optional.ofNullable(this.traceroute);
    }

    private SyntheticMonitoringCheckSettingsArgs() {}

    private SyntheticMonitoringCheckSettingsArgs(SyntheticMonitoringCheckSettingsArgs $) {
        this.dns = $.dns;
        this.http = $.http;
        this.ping = $.ping;
        this.tcp = $.tcp;
        this.traceroute = $.traceroute;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SyntheticMonitoringCheckSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SyntheticMonitoringCheckSettingsArgs $;

        public Builder() {
            $ = new SyntheticMonitoringCheckSettingsArgs();
        }

        public Builder(SyntheticMonitoringCheckSettingsArgs defaults) {
            $ = new SyntheticMonitoringCheckSettingsArgs(Objects.requireNonNull(defaults));
        }

        public Builder dns(@Nullable Output<SyntheticMonitoringCheckSettingsDnsArgs> dns) {
            $.dns = dns;
            return this;
        }

        public Builder dns(SyntheticMonitoringCheckSettingsDnsArgs dns) {
            return dns(Output.of(dns));
        }

        public Builder http(@Nullable Output<SyntheticMonitoringCheckSettingsHttpArgs> http) {
            $.http = http;
            return this;
        }

        public Builder http(SyntheticMonitoringCheckSettingsHttpArgs http) {
            return http(Output.of(http));
        }

        public Builder ping(@Nullable Output<SyntheticMonitoringCheckSettingsPingArgs> ping) {
            $.ping = ping;
            return this;
        }

        public Builder ping(SyntheticMonitoringCheckSettingsPingArgs ping) {
            return ping(Output.of(ping));
        }

        public Builder tcp(@Nullable Output<SyntheticMonitoringCheckSettingsTcpArgs> tcp) {
            $.tcp = tcp;
            return this;
        }

        public Builder tcp(SyntheticMonitoringCheckSettingsTcpArgs tcp) {
            return tcp(Output.of(tcp));
        }

        public Builder traceroute(@Nullable Output<SyntheticMonitoringCheckSettingsTracerouteArgs> traceroute) {
            $.traceroute = traceroute;
            return this;
        }

        public Builder traceroute(SyntheticMonitoringCheckSettingsTracerouteArgs traceroute) {
            return traceroute(Output.of(traceroute));
        }

        public SyntheticMonitoringCheckSettingsArgs build() {
            return $;
        }
    }

}
