// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface BuiltinRoleAssignmentRole {
    global?: pulumi.Input<boolean>;
    uid: pulumi.Input<string>;
}

export interface ContactPointAlertmanager {
    basicAuthPassword?: pulumi.Input<string>;
    basicAuthUser?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointDingding {
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    messageType?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointDiscord {
    avatarUrl?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
    useDiscordUsername?: pulumi.Input<boolean>;
}

export interface ContactPointEmail {
    addresses: pulumi.Input<pulumi.Input<string>[]>;
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    singleEmail?: pulumi.Input<boolean>;
    subject?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
}

export interface ContactPointGooglechat {
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointKafka {
    disableResolveMessage?: pulumi.Input<boolean>;
    restProxyUrl: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    topic: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
}

export interface ContactPointOpsgeny {
    apiKey: pulumi.Input<string>;
    autoClose?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    overridePriority?: pulumi.Input<boolean>;
    sendTagsAs?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface ContactPointPagerduty {
    class?: pulumi.Input<string>;
    component?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    group?: pulumi.Input<string>;
    integrationKey: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    severity?: pulumi.Input<string>;
    summary?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
}

export interface ContactPointPushover {
    apiToken: pulumi.Input<string>;
    device?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    expire?: pulumi.Input<number>;
    message?: pulumi.Input<string>;
    okPriority?: pulumi.Input<number>;
    okSound?: pulumi.Input<string>;
    priority?: pulumi.Input<number>;
    retry?: pulumi.Input<number>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    sound?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
    userKey: pulumi.Input<string>;
}

export interface ContactPointSensugo {
    apiKey: pulumi.Input<string>;
    check?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    entity?: pulumi.Input<string>;
    handler?: pulumi.Input<string>;
    message?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointSlack {
    disableResolveMessage?: pulumi.Input<boolean>;
    endpointUrl?: pulumi.Input<string>;
    iconEmoji?: pulumi.Input<string>;
    iconUrl?: pulumi.Input<string>;
    mentionChannel?: pulumi.Input<string>;
    mentionGroups?: pulumi.Input<string>;
    mentionUsers?: pulumi.Input<string>;
    recipient?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    text?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
    token?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
    username?: pulumi.Input<string>;
}

export interface ContactPointTeam {
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    sectionTitle?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    title?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointTelegram {
    chatId: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    token: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
}

export interface ContactPointThreema {
    apiSecret: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    gatewayId: pulumi.Input<string>;
    recipientId: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
}

export interface ContactPointVictorop {
    disableResolveMessage?: pulumi.Input<boolean>;
    messageType?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointWebhook {
    authorizationCredentials?: pulumi.Input<string>;
    authorizationScheme?: pulumi.Input<string>;
    basicAuthPassword?: pulumi.Input<string>;
    basicAuthUser?: pulumi.Input<string>;
    disableResolveMessage?: pulumi.Input<boolean>;
    httpMethod?: pulumi.Input<string>;
    maxAlerts?: pulumi.Input<number>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface ContactPointWecom {
    disableResolveMessage?: pulumi.Input<boolean>;
    message?: pulumi.Input<string>;
    settings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    title?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
    url: pulumi.Input<string>;
}

export interface DashboardPermissionPermission {
    permission: pulumi.Input<string>;
    role?: pulumi.Input<string>;
    teamId?: pulumi.Input<number>;
    userId?: pulumi.Input<number>;
}

export interface DataSourceJsonData {
    assumeRoleArn?: pulumi.Input<string>;
    authType?: pulumi.Input<string>;
    authenticationType?: pulumi.Input<string>;
    catalog?: pulumi.Input<string>;
    clientEmail?: pulumi.Input<string>;
    clientId?: pulumi.Input<string>;
    cloudName?: pulumi.Input<string>;
    connMaxLifetime?: pulumi.Input<number>;
    customMetricsNamespaces?: pulumi.Input<string>;
    database?: pulumi.Input<string>;
    defaultBucket?: pulumi.Input<string>;
    defaultProject?: pulumi.Input<string>;
    defaultRegion?: pulumi.Input<string>;
    derivedFields?: pulumi.Input<pulumi.Input<inputs.DataSourceJsonDataDerivedField>[]>;
    encrypt?: pulumi.Input<string>;
    esVersion?: pulumi.Input<string>;
    externalId?: pulumi.Input<string>;
    githubUrl?: pulumi.Input<string>;
    graphiteVersion?: pulumi.Input<string>;
    httpMethod?: pulumi.Input<string>;
    implementation?: pulumi.Input<string>;
    interval?: pulumi.Input<string>;
    logLevelField?: pulumi.Input<string>;
    logMessageField?: pulumi.Input<string>;
    manageAlerts?: pulumi.Input<boolean>;
    maxConcurrentShardRequests?: pulumi.Input<number>;
    maxIdleConns?: pulumi.Input<number>;
    maxLines?: pulumi.Input<number>;
    maxOpenConns?: pulumi.Input<number>;
    orgSlug?: pulumi.Input<string>;
    organization?: pulumi.Input<string>;
    outputLocation?: pulumi.Input<string>;
    postgresVersion?: pulumi.Input<number>;
    profile?: pulumi.Input<string>;
    queryTimeout?: pulumi.Input<string>;
    sigv4AssumeRoleArn?: pulumi.Input<string>;
    sigv4Auth?: pulumi.Input<boolean>;
    sigv4AuthType?: pulumi.Input<string>;
    sigv4ExternalId?: pulumi.Input<string>;
    sigv4Profile?: pulumi.Input<string>;
    sigv4Region?: pulumi.Input<string>;
    sslMode?: pulumi.Input<string>;
    subscriptionId?: pulumi.Input<string>;
    tenantId?: pulumi.Input<string>;
    timeField?: pulumi.Input<string>;
    timeInterval?: pulumi.Input<string>;
    timescaledb?: pulumi.Input<boolean>;
    tlsAuth?: pulumi.Input<boolean>;
    tlsAuthWithCaCert?: pulumi.Input<boolean>;
    tlsConfigurationMethod?: pulumi.Input<string>;
    tlsSkipVerify?: pulumi.Input<boolean>;
    tokenUri?: pulumi.Input<string>;
    tracingDatasourceUid?: pulumi.Input<string>;
    tsdbResolution?: pulumi.Input<number>;
    tsdbVersion?: pulumi.Input<number>;
    version?: pulumi.Input<string>;
    workgroup?: pulumi.Input<string>;
    xpackEnabled?: pulumi.Input<boolean>;
}

export interface DataSourceJsonDataDerivedField {
    datasourceUid?: pulumi.Input<string>;
    matcherRegex?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

export interface DataSourcePermissionPermission {
    permission: pulumi.Input<string>;
    teamId?: pulumi.Input<number>;
    userId?: pulumi.Input<number>;
}

export interface DataSourceSecureJsonData {
    accessKey?: pulumi.Input<string>;
    accessToken?: pulumi.Input<string>;
    authToken?: pulumi.Input<string>;
    basicAuthPassword?: pulumi.Input<string>;
    clientSecret?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    privateKey?: pulumi.Input<string>;
    secretKey?: pulumi.Input<string>;
    sigv4AccessKey?: pulumi.Input<string>;
    sigv4SecretKey?: pulumi.Input<string>;
    tlsCaCert?: pulumi.Input<string>;
    tlsClientCert?: pulumi.Input<string>;
    tlsClientKey?: pulumi.Input<string>;
}

export interface FolderPermissionPermission {
    permission: pulumi.Input<string>;
    role?: pulumi.Input<string>;
    teamId?: pulumi.Input<number>;
    userId?: pulumi.Input<number>;
}

export interface MuteTimingInterval {
    daysOfMonths?: pulumi.Input<pulumi.Input<string>[]>;
    months?: pulumi.Input<pulumi.Input<string>[]>;
    times?: pulumi.Input<pulumi.Input<inputs.MuteTimingIntervalTime>[]>;
    weekdays?: pulumi.Input<pulumi.Input<string>[]>;
    years?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface MuteTimingIntervalTime {
    end: pulumi.Input<string>;
    start: pulumi.Input<string>;
}

export interface NotificationPolicyPolicy {
    contactPoint: pulumi.Input<string>;
    continue?: pulumi.Input<boolean>;
    groupBies: pulumi.Input<pulumi.Input<string>[]>;
    groupInterval?: pulumi.Input<string>;
    groupWait?: pulumi.Input<string>;
    matchers?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyMatcher>[]>;
    muteTimings?: pulumi.Input<pulumi.Input<string>[]>;
    policies?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyPolicy>[]>;
    repeatInterval?: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyMatcher {
    label: pulumi.Input<string>;
    match: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyPolicy {
    contactPoint: pulumi.Input<string>;
    continue?: pulumi.Input<boolean>;
    groupBies: pulumi.Input<pulumi.Input<string>[]>;
    groupInterval?: pulumi.Input<string>;
    groupWait?: pulumi.Input<string>;
    matchers?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyPolicyMatcher>[]>;
    muteTimings?: pulumi.Input<pulumi.Input<string>[]>;
    policies?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyPolicyPolicy>[]>;
    repeatInterval?: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyPolicyMatcher {
    label: pulumi.Input<string>;
    match: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyPolicyPolicy {
    contactPoint: pulumi.Input<string>;
    continue?: pulumi.Input<boolean>;
    groupBies: pulumi.Input<pulumi.Input<string>[]>;
    groupInterval?: pulumi.Input<string>;
    groupWait?: pulumi.Input<string>;
    matchers?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyPolicyPolicyMatcher>[]>;
    muteTimings?: pulumi.Input<pulumi.Input<string>[]>;
    policies?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyPolicyPolicyPolicy>[]>;
    repeatInterval?: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyPolicyPolicyMatcher {
    label: pulumi.Input<string>;
    match: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyPolicyPolicyPolicy {
    contactPoint: pulumi.Input<string>;
    continue?: pulumi.Input<boolean>;
    groupBies: pulumi.Input<pulumi.Input<string>[]>;
    groupInterval?: pulumi.Input<string>;
    groupWait?: pulumi.Input<string>;
    matchers?: pulumi.Input<pulumi.Input<inputs.NotificationPolicyPolicyPolicyPolicyPolicyMatcher>[]>;
    muteTimings?: pulumi.Input<pulumi.Input<string>[]>;
    repeatInterval?: pulumi.Input<string>;
}

export interface NotificationPolicyPolicyPolicyPolicyPolicyMatcher {
    label: pulumi.Input<string>;
    match: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface OncallIntegrationDefaultRoute {
    escalationChainId?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    slack?: pulumi.Input<inputs.OncallIntegrationDefaultRouteSlack>;
}

export interface OncallIntegrationDefaultRouteSlack {
    channelId: pulumi.Input<string>;
}

export interface OncallIntegrationTemplates {
    groupingKey?: pulumi.Input<string>;
    resolveSignal?: pulumi.Input<string>;
    slack?: pulumi.Input<inputs.OncallIntegrationTemplatesSlack>;
}

export interface OncallIntegrationTemplatesSlack {
    imageUrl?: pulumi.Input<string>;
    message?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
}

export interface OncallRouteSlack {
    channelId: pulumi.Input<string>;
}

export interface OncallScheduleSlack {
    channelId?: pulumi.Input<string>;
    userGroupId?: pulumi.Input<string>;
}

export interface PlaylistItem {
    id?: pulumi.Input<string>;
    order: pulumi.Input<number>;
    title: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface ReportSchedule {
    customInterval?: pulumi.Input<string>;
    endTime?: pulumi.Input<string>;
    frequency: pulumi.Input<string>;
    startTime?: pulumi.Input<string>;
    workdaysOnly?: pulumi.Input<boolean>;
}

export interface ReportTimeRange {
    from?: pulumi.Input<string>;
    to?: pulumi.Input<string>;
}

export interface RolePermission {
    action: pulumi.Input<string>;
    scope?: pulumi.Input<string>;
}

export interface RuleGroupRule {
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    condition: pulumi.Input<string>;
    datas: pulumi.Input<pulumi.Input<inputs.RuleGroupRuleData>[]>;
    execErrState?: pulumi.Input<string>;
    for?: pulumi.Input<string>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name: pulumi.Input<string>;
    noDataState?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
}

export interface RuleGroupRuleData {
    datasourceUid: pulumi.Input<string>;
    model: pulumi.Input<string>;
    queryType?: pulumi.Input<string>;
    refId: pulumi.Input<string>;
    relativeTimeRange: pulumi.Input<inputs.RuleGroupRuleDataRelativeTimeRange>;
}

export interface RuleGroupRuleDataRelativeTimeRange {
    from: pulumi.Input<number>;
    to: pulumi.Input<number>;
}

export interface SyntheticMonitoringCheckSettings {
    dns?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsDns>;
    http?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsHttp>;
    ping?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsPing>;
    tcp?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsTcp>;
    traceroute?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsTraceroute>;
}

export interface SyntheticMonitoringCheckSettingsDns {
    ipVersion?: pulumi.Input<string>;
    port?: pulumi.Input<number>;
    protocol?: pulumi.Input<string>;
    recordType?: pulumi.Input<string>;
    server?: pulumi.Input<string>;
    sourceIpAddress?: pulumi.Input<string>;
    validRCodes?: pulumi.Input<pulumi.Input<string>[]>;
    validateAdditionalRrs?: pulumi.Input<pulumi.Input<inputs.SyntheticMonitoringCheckSettingsDnsValidateAdditionalRr>[]>;
    validateAnswerRrs?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsDnsValidateAnswerRrs>;
    validateAuthorityRrs?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsDnsValidateAuthorityRrs>;
}

export interface SyntheticMonitoringCheckSettingsDnsValidateAdditionalRr {
    failIfMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
    failIfNotMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface SyntheticMonitoringCheckSettingsDnsValidateAnswerRrs {
    failIfMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
    failIfNotMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface SyntheticMonitoringCheckSettingsDnsValidateAuthorityRrs {
    failIfMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
    failIfNotMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface SyntheticMonitoringCheckSettingsHttp {
    basicAuth?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsHttpBasicAuth>;
    bearerToken?: pulumi.Input<string>;
    body?: pulumi.Input<string>;
    cacheBustingQueryParamName?: pulumi.Input<string>;
    failIfBodyMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
    failIfBodyNotMatchesRegexps?: pulumi.Input<pulumi.Input<string>[]>;
    failIfHeaderMatchesRegexps?: pulumi.Input<pulumi.Input<inputs.SyntheticMonitoringCheckSettingsHttpFailIfHeaderMatchesRegexp>[]>;
    failIfHeaderNotMatchesRegexps?: pulumi.Input<pulumi.Input<inputs.SyntheticMonitoringCheckSettingsHttpFailIfHeaderNotMatchesRegexp>[]>;
    failIfNotSsl?: pulumi.Input<boolean>;
    failIfSsl?: pulumi.Input<boolean>;
    headers?: pulumi.Input<pulumi.Input<string>[]>;
    ipVersion?: pulumi.Input<string>;
    method?: pulumi.Input<string>;
    noFollowRedirects?: pulumi.Input<boolean>;
    proxyUrl?: pulumi.Input<string>;
    tlsConfig?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsHttpTlsConfig>;
    validHttpVersions?: pulumi.Input<pulumi.Input<string>[]>;
    validStatusCodes?: pulumi.Input<pulumi.Input<number>[]>;
}

export interface SyntheticMonitoringCheckSettingsHttpBasicAuth {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface SyntheticMonitoringCheckSettingsHttpFailIfHeaderMatchesRegexp {
    allowMissing?: pulumi.Input<boolean>;
    header: pulumi.Input<string>;
    regexp: pulumi.Input<string>;
}

export interface SyntheticMonitoringCheckSettingsHttpFailIfHeaderNotMatchesRegexp {
    allowMissing?: pulumi.Input<boolean>;
    header: pulumi.Input<string>;
    regexp: pulumi.Input<string>;
}

export interface SyntheticMonitoringCheckSettingsHttpTlsConfig {
    caCert?: pulumi.Input<string>;
    clientCert?: pulumi.Input<string>;
    clientKey?: pulumi.Input<string>;
    insecureSkipVerify?: pulumi.Input<boolean>;
    serverName?: pulumi.Input<string>;
}

export interface SyntheticMonitoringCheckSettingsPing {
    dontFragment?: pulumi.Input<boolean>;
    ipVersion?: pulumi.Input<string>;
    payloadSize?: pulumi.Input<number>;
    sourceIpAddress?: pulumi.Input<string>;
}

export interface SyntheticMonitoringCheckSettingsTcp {
    ipVersion?: pulumi.Input<string>;
    queryResponses?: pulumi.Input<pulumi.Input<inputs.SyntheticMonitoringCheckSettingsTcpQueryResponse>[]>;
    sourceIpAddress?: pulumi.Input<string>;
    tls?: pulumi.Input<boolean>;
    tlsConfig?: pulumi.Input<inputs.SyntheticMonitoringCheckSettingsTcpTlsConfig>;
}

export interface SyntheticMonitoringCheckSettingsTcpQueryResponse {
    expect: pulumi.Input<string>;
    send: pulumi.Input<string>;
    startTls?: pulumi.Input<boolean>;
}

export interface SyntheticMonitoringCheckSettingsTcpTlsConfig {
    caCert?: pulumi.Input<string>;
    clientCert?: pulumi.Input<string>;
    clientKey?: pulumi.Input<string>;
    insecureSkipVerify?: pulumi.Input<boolean>;
    serverName?: pulumi.Input<string>;
}

export interface SyntheticMonitoringCheckSettingsTraceroute {
    maxHops?: pulumi.Input<number>;
    maxUnknownHops?: pulumi.Input<number>;
    ptrLookup?: pulumi.Input<boolean>;
}
