// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package grafana

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// * [HTTP API](https://grafana.com/docs/grafana-cloud/oncall/oncall-api-reference/outgoing_webhooks/)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-grafana/sdk/go/grafana"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-grafana/sdk/go/grafana"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := grafana.GetOncallOutgoingWebhook(ctx, &GetOncallOutgoingWebhookArgs{
//				Name: "example_outgoing_webhook",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetOncallOutgoingWebhook(ctx *pulumi.Context, args *GetOncallOutgoingWebhookArgs, opts ...pulumi.InvokeOption) (*GetOncallOutgoingWebhookResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetOncallOutgoingWebhookResult
	err := ctx.Invoke("grafana:index/getOncallOutgoingWebhook:getOncallOutgoingWebhook", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOncallOutgoingWebhook.
type GetOncallOutgoingWebhookArgs struct {
	// The outgoing webhook name.
	Name string `pulumi:"name"`
}

// A collection of values returned by getOncallOutgoingWebhook.
type GetOncallOutgoingWebhookResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The outgoing webhook name.
	Name string `pulumi:"name"`
}

func GetOncallOutgoingWebhookOutput(ctx *pulumi.Context, args GetOncallOutgoingWebhookOutputArgs, opts ...pulumi.InvokeOption) GetOncallOutgoingWebhookResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetOncallOutgoingWebhookResult, error) {
			args := v.(GetOncallOutgoingWebhookArgs)
			r, err := GetOncallOutgoingWebhook(ctx, &args, opts...)
			var s GetOncallOutgoingWebhookResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetOncallOutgoingWebhookResultOutput)
}

// A collection of arguments for invoking getOncallOutgoingWebhook.
type GetOncallOutgoingWebhookOutputArgs struct {
	// The outgoing webhook name.
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetOncallOutgoingWebhookOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOncallOutgoingWebhookArgs)(nil)).Elem()
}

// A collection of values returned by getOncallOutgoingWebhook.
type GetOncallOutgoingWebhookResultOutput struct{ *pulumi.OutputState }

func (GetOncallOutgoingWebhookResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOncallOutgoingWebhookResult)(nil)).Elem()
}

func (o GetOncallOutgoingWebhookResultOutput) ToGetOncallOutgoingWebhookResultOutput() GetOncallOutgoingWebhookResultOutput {
	return o
}

func (o GetOncallOutgoingWebhookResultOutput) ToGetOncallOutgoingWebhookResultOutputWithContext(ctx context.Context) GetOncallOutgoingWebhookResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetOncallOutgoingWebhookResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOncallOutgoingWebhookResult) string { return v.Id }).(pulumi.StringOutput)
}

// The outgoing webhook name.
func (o GetOncallOutgoingWebhookResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetOncallOutgoingWebhookResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOncallOutgoingWebhookResultOutput{})
}
