// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package grafana

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type OncallShift struct {
	pulumi.CustomResourceState

	// This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	ByDays pulumi.StringArrayOutput `pulumi:"byDays"`
	// This parameter takes a list of days of the month. Valid values are 1 to 31 or -31 to -1
	ByMonthdays pulumi.IntArrayOutput `pulumi:"byMonthdays"`
	// This parameter takes a list of months. Valid values are 1 to 12
	ByMonths pulumi.IntArrayOutput `pulumi:"byMonths"`
	// The duration of the event.
	Duration pulumi.IntOutput `pulumi:"duration"`
	// The frequency of the event. Can be daily, weekly, monthly
	Frequency pulumi.StringPtrOutput `pulumi:"frequency"`
	// The positive integer representing at which intervals the recurrence rule repeats.
	Interval pulumi.IntPtrOutput `pulumi:"interval"`
	// The priority level. The higher the value, the higher the priority.
	Level pulumi.IntPtrOutput `pulumi:"level"`
	// The shift's name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The list of lists with on-call users (for rolling_users event type)
	RollingUsers pulumi.StringArrayArrayOutput `pulumi:"rollingUsers"`
	// The start time of the on-call shift. This parameter takes a date format as yyyy-MM-dd'T'HH:mm:ss (for example
	// "2020-09-05T08:00:00")
	Start pulumi.StringOutput `pulumi:"start"`
	// The index of the list of users in rolling_users, from which on-call rotation starts.
	StartRotationFromUserIndex pulumi.IntPtrOutput `pulumi:"startRotationFromUserIndex"`
	// The ID of the team.
	TeamId pulumi.StringPtrOutput `pulumi:"teamId"`
	// The shift's timezone. Overrides schedule's timezone.
	TimeZone pulumi.StringPtrOutput `pulumi:"timeZone"`
	// The shift's type. Can be rolling_users, recurrent_event, single_event
	Type pulumi.StringOutput `pulumi:"type"`
	// The list of on-call users (for single_event and recurrent_event event type).
	Users pulumi.StringArrayOutput `pulumi:"users"`
	// Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	WeekStart pulumi.StringPtrOutput `pulumi:"weekStart"`
}

// NewOncallShift registers a new resource with the given unique name, arguments, and options.
func NewOncallShift(ctx *pulumi.Context,
	name string, args *OncallShiftArgs, opts ...pulumi.ResourceOption) (*OncallShift, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Duration == nil {
		return nil, errors.New("invalid value for required argument 'Duration'")
	}
	if args.Start == nil {
		return nil, errors.New("invalid value for required argument 'Start'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource OncallShift
	err := ctx.RegisterResource("grafana:index/oncallShift:OncallShift", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOncallShift gets an existing OncallShift resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOncallShift(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OncallShiftState, opts ...pulumi.ResourceOption) (*OncallShift, error) {
	var resource OncallShift
	err := ctx.ReadResource("grafana:index/oncallShift:OncallShift", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OncallShift resources.
type oncallShiftState struct {
	// This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	ByDays []string `pulumi:"byDays"`
	// This parameter takes a list of days of the month. Valid values are 1 to 31 or -31 to -1
	ByMonthdays []int `pulumi:"byMonthdays"`
	// This parameter takes a list of months. Valid values are 1 to 12
	ByMonths []int `pulumi:"byMonths"`
	// The duration of the event.
	Duration *int `pulumi:"duration"`
	// The frequency of the event. Can be daily, weekly, monthly
	Frequency *string `pulumi:"frequency"`
	// The positive integer representing at which intervals the recurrence rule repeats.
	Interval *int `pulumi:"interval"`
	// The priority level. The higher the value, the higher the priority.
	Level *int `pulumi:"level"`
	// The shift's name.
	Name *string `pulumi:"name"`
	// The list of lists with on-call users (for rolling_users event type)
	RollingUsers [][]string `pulumi:"rollingUsers"`
	// The start time of the on-call shift. This parameter takes a date format as yyyy-MM-dd'T'HH:mm:ss (for example
	// "2020-09-05T08:00:00")
	Start *string `pulumi:"start"`
	// The index of the list of users in rolling_users, from which on-call rotation starts.
	StartRotationFromUserIndex *int `pulumi:"startRotationFromUserIndex"`
	// The ID of the team.
	TeamId *string `pulumi:"teamId"`
	// The shift's timezone. Overrides schedule's timezone.
	TimeZone *string `pulumi:"timeZone"`
	// The shift's type. Can be rolling_users, recurrent_event, single_event
	Type *string `pulumi:"type"`
	// The list of on-call users (for single_event and recurrent_event event type).
	Users []string `pulumi:"users"`
	// Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	WeekStart *string `pulumi:"weekStart"`
}

type OncallShiftState struct {
	// This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	ByDays pulumi.StringArrayInput
	// This parameter takes a list of days of the month. Valid values are 1 to 31 or -31 to -1
	ByMonthdays pulumi.IntArrayInput
	// This parameter takes a list of months. Valid values are 1 to 12
	ByMonths pulumi.IntArrayInput
	// The duration of the event.
	Duration pulumi.IntPtrInput
	// The frequency of the event. Can be daily, weekly, monthly
	Frequency pulumi.StringPtrInput
	// The positive integer representing at which intervals the recurrence rule repeats.
	Interval pulumi.IntPtrInput
	// The priority level. The higher the value, the higher the priority.
	Level pulumi.IntPtrInput
	// The shift's name.
	Name pulumi.StringPtrInput
	// The list of lists with on-call users (for rolling_users event type)
	RollingUsers pulumi.StringArrayArrayInput
	// The start time of the on-call shift. This parameter takes a date format as yyyy-MM-dd'T'HH:mm:ss (for example
	// "2020-09-05T08:00:00")
	Start pulumi.StringPtrInput
	// The index of the list of users in rolling_users, from which on-call rotation starts.
	StartRotationFromUserIndex pulumi.IntPtrInput
	// The ID of the team.
	TeamId pulumi.StringPtrInput
	// The shift's timezone. Overrides schedule's timezone.
	TimeZone pulumi.StringPtrInput
	// The shift's type. Can be rolling_users, recurrent_event, single_event
	Type pulumi.StringPtrInput
	// The list of on-call users (for single_event and recurrent_event event type).
	Users pulumi.StringArrayInput
	// Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	WeekStart pulumi.StringPtrInput
}

func (OncallShiftState) ElementType() reflect.Type {
	return reflect.TypeOf((*oncallShiftState)(nil)).Elem()
}

type oncallShiftArgs struct {
	// This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	ByDays []string `pulumi:"byDays"`
	// This parameter takes a list of days of the month. Valid values are 1 to 31 or -31 to -1
	ByMonthdays []int `pulumi:"byMonthdays"`
	// This parameter takes a list of months. Valid values are 1 to 12
	ByMonths []int `pulumi:"byMonths"`
	// The duration of the event.
	Duration int `pulumi:"duration"`
	// The frequency of the event. Can be daily, weekly, monthly
	Frequency *string `pulumi:"frequency"`
	// The positive integer representing at which intervals the recurrence rule repeats.
	Interval *int `pulumi:"interval"`
	// The priority level. The higher the value, the higher the priority.
	Level *int `pulumi:"level"`
	// The shift's name.
	Name *string `pulumi:"name"`
	// The list of lists with on-call users (for rolling_users event type)
	RollingUsers [][]string `pulumi:"rollingUsers"`
	// The start time of the on-call shift. This parameter takes a date format as yyyy-MM-dd'T'HH:mm:ss (for example
	// "2020-09-05T08:00:00")
	Start string `pulumi:"start"`
	// The index of the list of users in rolling_users, from which on-call rotation starts.
	StartRotationFromUserIndex *int `pulumi:"startRotationFromUserIndex"`
	// The ID of the team.
	TeamId *string `pulumi:"teamId"`
	// The shift's timezone. Overrides schedule's timezone.
	TimeZone *string `pulumi:"timeZone"`
	// The shift's type. Can be rolling_users, recurrent_event, single_event
	Type string `pulumi:"type"`
	// The list of on-call users (for single_event and recurrent_event event type).
	Users []string `pulumi:"users"`
	// Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	WeekStart *string `pulumi:"weekStart"`
}

// The set of arguments for constructing a OncallShift resource.
type OncallShiftArgs struct {
	// This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	ByDays pulumi.StringArrayInput
	// This parameter takes a list of days of the month. Valid values are 1 to 31 or -31 to -1
	ByMonthdays pulumi.IntArrayInput
	// This parameter takes a list of months. Valid values are 1 to 12
	ByMonths pulumi.IntArrayInput
	// The duration of the event.
	Duration pulumi.IntInput
	// The frequency of the event. Can be daily, weekly, monthly
	Frequency pulumi.StringPtrInput
	// The positive integer representing at which intervals the recurrence rule repeats.
	Interval pulumi.IntPtrInput
	// The priority level. The higher the value, the higher the priority.
	Level pulumi.IntPtrInput
	// The shift's name.
	Name pulumi.StringPtrInput
	// The list of lists with on-call users (for rolling_users event type)
	RollingUsers pulumi.StringArrayArrayInput
	// The start time of the on-call shift. This parameter takes a date format as yyyy-MM-dd'T'HH:mm:ss (for example
	// "2020-09-05T08:00:00")
	Start pulumi.StringInput
	// The index of the list of users in rolling_users, from which on-call rotation starts.
	StartRotationFromUserIndex pulumi.IntPtrInput
	// The ID of the team.
	TeamId pulumi.StringPtrInput
	// The shift's timezone. Overrides schedule's timezone.
	TimeZone pulumi.StringPtrInput
	// The shift's type. Can be rolling_users, recurrent_event, single_event
	Type pulumi.StringInput
	// The list of on-call users (for single_event and recurrent_event event type).
	Users pulumi.StringArrayInput
	// Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
	WeekStart pulumi.StringPtrInput
}

func (OncallShiftArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*oncallShiftArgs)(nil)).Elem()
}

type OncallShiftInput interface {
	pulumi.Input

	ToOncallShiftOutput() OncallShiftOutput
	ToOncallShiftOutputWithContext(ctx context.Context) OncallShiftOutput
}

func (*OncallShift) ElementType() reflect.Type {
	return reflect.TypeOf((**OncallShift)(nil)).Elem()
}

func (i *OncallShift) ToOncallShiftOutput() OncallShiftOutput {
	return i.ToOncallShiftOutputWithContext(context.Background())
}

func (i *OncallShift) ToOncallShiftOutputWithContext(ctx context.Context) OncallShiftOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OncallShiftOutput)
}

// OncallShiftArrayInput is an input type that accepts OncallShiftArray and OncallShiftArrayOutput values.
// You can construct a concrete instance of `OncallShiftArrayInput` via:
//
//	OncallShiftArray{ OncallShiftArgs{...} }
type OncallShiftArrayInput interface {
	pulumi.Input

	ToOncallShiftArrayOutput() OncallShiftArrayOutput
	ToOncallShiftArrayOutputWithContext(context.Context) OncallShiftArrayOutput
}

type OncallShiftArray []OncallShiftInput

func (OncallShiftArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OncallShift)(nil)).Elem()
}

func (i OncallShiftArray) ToOncallShiftArrayOutput() OncallShiftArrayOutput {
	return i.ToOncallShiftArrayOutputWithContext(context.Background())
}

func (i OncallShiftArray) ToOncallShiftArrayOutputWithContext(ctx context.Context) OncallShiftArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OncallShiftArrayOutput)
}

// OncallShiftMapInput is an input type that accepts OncallShiftMap and OncallShiftMapOutput values.
// You can construct a concrete instance of `OncallShiftMapInput` via:
//
//	OncallShiftMap{ "key": OncallShiftArgs{...} }
type OncallShiftMapInput interface {
	pulumi.Input

	ToOncallShiftMapOutput() OncallShiftMapOutput
	ToOncallShiftMapOutputWithContext(context.Context) OncallShiftMapOutput
}

type OncallShiftMap map[string]OncallShiftInput

func (OncallShiftMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OncallShift)(nil)).Elem()
}

func (i OncallShiftMap) ToOncallShiftMapOutput() OncallShiftMapOutput {
	return i.ToOncallShiftMapOutputWithContext(context.Background())
}

func (i OncallShiftMap) ToOncallShiftMapOutputWithContext(ctx context.Context) OncallShiftMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OncallShiftMapOutput)
}

type OncallShiftOutput struct{ *pulumi.OutputState }

func (OncallShiftOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OncallShift)(nil)).Elem()
}

func (o OncallShiftOutput) ToOncallShiftOutput() OncallShiftOutput {
	return o
}

func (o OncallShiftOutput) ToOncallShiftOutputWithContext(ctx context.Context) OncallShiftOutput {
	return o
}

// This parameter takes a list of days in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
func (o OncallShiftOutput) ByDays() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringArrayOutput { return v.ByDays }).(pulumi.StringArrayOutput)
}

// This parameter takes a list of days of the month. Valid values are 1 to 31 or -31 to -1
func (o OncallShiftOutput) ByMonthdays() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.IntArrayOutput { return v.ByMonthdays }).(pulumi.IntArrayOutput)
}

// This parameter takes a list of months. Valid values are 1 to 12
func (o OncallShiftOutput) ByMonths() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.IntArrayOutput { return v.ByMonths }).(pulumi.IntArrayOutput)
}

// The duration of the event.
func (o OncallShiftOutput) Duration() pulumi.IntOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.IntOutput { return v.Duration }).(pulumi.IntOutput)
}

// The frequency of the event. Can be daily, weekly, monthly
func (o OncallShiftOutput) Frequency() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringPtrOutput { return v.Frequency }).(pulumi.StringPtrOutput)
}

// The positive integer representing at which intervals the recurrence rule repeats.
func (o OncallShiftOutput) Interval() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.IntPtrOutput { return v.Interval }).(pulumi.IntPtrOutput)
}

// The priority level. The higher the value, the higher the priority.
func (o OncallShiftOutput) Level() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.IntPtrOutput { return v.Level }).(pulumi.IntPtrOutput)
}

// The shift's name.
func (o OncallShiftOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The list of lists with on-call users (for rolling_users event type)
func (o OncallShiftOutput) RollingUsers() pulumi.StringArrayArrayOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringArrayArrayOutput { return v.RollingUsers }).(pulumi.StringArrayArrayOutput)
}

// The start time of the on-call shift. This parameter takes a date format as yyyy-MM-dd'T'HH:mm:ss (for example
// "2020-09-05T08:00:00")
func (o OncallShiftOutput) Start() pulumi.StringOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringOutput { return v.Start }).(pulumi.StringOutput)
}

// The index of the list of users in rolling_users, from which on-call rotation starts.
func (o OncallShiftOutput) StartRotationFromUserIndex() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.IntPtrOutput { return v.StartRotationFromUserIndex }).(pulumi.IntPtrOutput)
}

// The ID of the team.
func (o OncallShiftOutput) TeamId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringPtrOutput { return v.TeamId }).(pulumi.StringPtrOutput)
}

// The shift's timezone. Overrides schedule's timezone.
func (o OncallShiftOutput) TimeZone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringPtrOutput { return v.TimeZone }).(pulumi.StringPtrOutput)
}

// The shift's type. Can be rolling_users, recurrent_event, single_event
func (o OncallShiftOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// The list of on-call users (for single_event and recurrent_event event type).
func (o OncallShiftOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringArrayOutput { return v.Users }).(pulumi.StringArrayOutput)
}

// Start day of the week in iCal format. Can be MO, TU, WE, TH, FR, SA, SU
func (o OncallShiftOutput) WeekStart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OncallShift) pulumi.StringPtrOutput { return v.WeekStart }).(pulumi.StringPtrOutput)
}

type OncallShiftArrayOutput struct{ *pulumi.OutputState }

func (OncallShiftArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OncallShift)(nil)).Elem()
}

func (o OncallShiftArrayOutput) ToOncallShiftArrayOutput() OncallShiftArrayOutput {
	return o
}

func (o OncallShiftArrayOutput) ToOncallShiftArrayOutputWithContext(ctx context.Context) OncallShiftArrayOutput {
	return o
}

func (o OncallShiftArrayOutput) Index(i pulumi.IntInput) OncallShiftOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OncallShift {
		return vs[0].([]*OncallShift)[vs[1].(int)]
	}).(OncallShiftOutput)
}

type OncallShiftMapOutput struct{ *pulumi.OutputState }

func (OncallShiftMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OncallShift)(nil)).Elem()
}

func (o OncallShiftMapOutput) ToOncallShiftMapOutput() OncallShiftMapOutput {
	return o
}

func (o OncallShiftMapOutput) ToOncallShiftMapOutputWithContext(ctx context.Context) OncallShiftMapOutput {
	return o
}

func (o OncallShiftMapOutput) MapIndex(k pulumi.StringInput) OncallShiftOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OncallShift {
		return vs[0].(map[string]*OncallShift)[vs[1].(string)]
	}).(OncallShiftOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OncallShiftInput)(nil)).Elem(), &OncallShift{})
	pulumi.RegisterInputType(reflect.TypeOf((*OncallShiftArrayInput)(nil)).Elem(), OncallShiftArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OncallShiftMapInput)(nil)).Elem(), OncallShiftMap{})
	pulumi.RegisterOutputType(OncallShiftOutput{})
	pulumi.RegisterOutputType(OncallShiftArrayOutput{})
	pulumi.RegisterOutputType(OncallShiftMapOutput{})
}
