// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class ContactPointWecomArgs : global::Pulumi.ResourceArgs
    {
        [Input("disableResolveMessage")]
        public Input<bool>? DisableResolveMessage { get; set; }

        [Input("message")]
        public Input<string>? Message { get; set; }

        [Input("settings")]
        private InputMap<string>? _settings;
        public InputMap<string> Settings
        {
            get => _settings ?? (_settings = new InputMap<string>());
            set => _settings = value;
        }

        [Input("title")]
        public Input<string>? Title { get; set; }

        [Input("uid")]
        public Input<string>? Uid { get; set; }

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public ContactPointWecomArgs()
        {
        }
        public static new ContactPointWecomArgs Empty => new ContactPointWecomArgs();
    }
}
