// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class ContactPointWebhookArgs : global::Pulumi.ResourceArgs
    {
        [Input("authorizationCredentials")]
        public Input<string>? AuthorizationCredentials { get; set; }

        [Input("authorizationScheme")]
        public Input<string>? AuthorizationScheme { get; set; }

        [Input("basicAuthPassword")]
        public Input<string>? BasicAuthPassword { get; set; }

        [Input("basicAuthUser")]
        public Input<string>? BasicAuthUser { get; set; }

        [Input("disableResolveMessage")]
        public Input<bool>? DisableResolveMessage { get; set; }

        [Input("httpMethod")]
        public Input<string>? HttpMethod { get; set; }

        [Input("maxAlerts")]
        public Input<int>? MaxAlerts { get; set; }

        [Input("settings")]
        private InputMap<string>? _settings;
        public InputMap<string> Settings
        {
            get => _settings ?? (_settings = new InputMap<string>());
            set => _settings = value;
        }

        [Input("uid")]
        public Input<string>? Uid { get; set; }

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public ContactPointWebhookArgs()
        {
        }
        public static new ContactPointWebhookArgs Empty => new ContactPointWebhookArgs();
    }
}
