// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class DataSourceJsonDataArgs : global::Pulumi.ResourceArgs
    {
        [Input("assumeRoleArn")]
        public Input<string>? AssumeRoleArn { get; set; }

        [Input("authType")]
        public Input<string>? AuthType { get; set; }

        [Input("authenticationType")]
        public Input<string>? AuthenticationType { get; set; }

        [Input("catalog")]
        public Input<string>? Catalog { get; set; }

        [Input("clientEmail")]
        public Input<string>? ClientEmail { get; set; }

        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        [Input("cloudName")]
        public Input<string>? CloudName { get; set; }

        [Input("connMaxLifetime")]
        public Input<int>? ConnMaxLifetime { get; set; }

        [Input("customMetricsNamespaces")]
        public Input<string>? CustomMetricsNamespaces { get; set; }

        [Input("database")]
        public Input<string>? Database { get; set; }

        [Input("defaultBucket")]
        public Input<string>? DefaultBucket { get; set; }

        [Input("defaultProject")]
        public Input<string>? DefaultProject { get; set; }

        [Input("defaultRegion")]
        public Input<string>? DefaultRegion { get; set; }

        [Input("derivedFields")]
        private InputList<Inputs.DataSourceJsonDataDerivedFieldArgs>? _derivedFields;
        public InputList<Inputs.DataSourceJsonDataDerivedFieldArgs> DerivedFields
        {
            get => _derivedFields ?? (_derivedFields = new InputList<Inputs.DataSourceJsonDataDerivedFieldArgs>());
            set => _derivedFields = value;
        }

        [Input("encrypt")]
        public Input<string>? Encrypt { get; set; }

        [Input("esVersion")]
        public Input<string>? EsVersion { get; set; }

        [Input("externalId")]
        public Input<string>? ExternalId { get; set; }

        [Input("githubUrl")]
        public Input<string>? GithubUrl { get; set; }

        [Input("graphiteVersion")]
        public Input<string>? GraphiteVersion { get; set; }

        [Input("httpMethod")]
        public Input<string>? HttpMethod { get; set; }

        [Input("implementation")]
        public Input<string>? Implementation { get; set; }

        [Input("interval")]
        public Input<string>? Interval { get; set; }

        [Input("logLevelField")]
        public Input<string>? LogLevelField { get; set; }

        [Input("logMessageField")]
        public Input<string>? LogMessageField { get; set; }

        [Input("manageAlerts")]
        public Input<bool>? ManageAlerts { get; set; }

        [Input("maxConcurrentShardRequests")]
        public Input<int>? MaxConcurrentShardRequests { get; set; }

        [Input("maxIdleConns")]
        public Input<int>? MaxIdleConns { get; set; }

        [Input("maxLines")]
        public Input<int>? MaxLines { get; set; }

        [Input("maxOpenConns")]
        public Input<int>? MaxOpenConns { get; set; }

        [Input("orgSlug")]
        public Input<string>? OrgSlug { get; set; }

        [Input("organization")]
        public Input<string>? Organization { get; set; }

        [Input("outputLocation")]
        public Input<string>? OutputLocation { get; set; }

        [Input("postgresVersion")]
        public Input<int>? PostgresVersion { get; set; }

        [Input("profile")]
        public Input<string>? Profile { get; set; }

        [Input("queryTimeout")]
        public Input<string>? QueryTimeout { get; set; }

        [Input("sigv4AssumeRoleArn")]
        public Input<string>? Sigv4AssumeRoleArn { get; set; }

        [Input("sigv4Auth")]
        public Input<bool>? Sigv4Auth { get; set; }

        [Input("sigv4AuthType")]
        public Input<string>? Sigv4AuthType { get; set; }

        [Input("sigv4ExternalId")]
        public Input<string>? Sigv4ExternalId { get; set; }

        [Input("sigv4Profile")]
        public Input<string>? Sigv4Profile { get; set; }

        [Input("sigv4Region")]
        public Input<string>? Sigv4Region { get; set; }

        [Input("sslMode")]
        public Input<string>? SslMode { get; set; }

        [Input("subscriptionId")]
        public Input<string>? SubscriptionId { get; set; }

        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        [Input("timeField")]
        public Input<string>? TimeField { get; set; }

        [Input("timeInterval")]
        public Input<string>? TimeInterval { get; set; }

        [Input("timescaledb")]
        public Input<bool>? Timescaledb { get; set; }

        [Input("tlsAuth")]
        public Input<bool>? TlsAuth { get; set; }

        [Input("tlsAuthWithCaCert")]
        public Input<bool>? TlsAuthWithCaCert { get; set; }

        [Input("tlsConfigurationMethod")]
        public Input<string>? TlsConfigurationMethod { get; set; }

        [Input("tlsSkipVerify")]
        public Input<bool>? TlsSkipVerify { get; set; }

        [Input("tokenUri")]
        public Input<string>? TokenUri { get; set; }

        [Input("tracingDatasourceUid")]
        public Input<string>? TracingDatasourceUid { get; set; }

        [Input("tsdbResolution")]
        public Input<int>? TsdbResolution { get; set; }

        [Input("tsdbVersion")]
        public Input<int>? TsdbVersion { get; set; }

        [Input("version")]
        public Input<string>? Version { get; set; }

        [Input("workgroup")]
        public Input<string>? Workgroup { get; set; }

        [Input("xpackEnabled")]
        public Input<bool>? XpackEnabled { get; set; }

        public DataSourceJsonDataArgs()
        {
        }
        public static new DataSourceJsonDataArgs Empty => new DataSourceJsonDataArgs();
    }
}
