// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class DataSourceSecureJsonDataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKey")]
        public Input<string>? AccessKey { get; set; }

        [Input("accessToken")]
        public Input<string>? AccessToken { get; set; }

        [Input("authToken")]
        public Input<string>? AuthToken { get; set; }

        [Input("basicAuthPassword")]
        public Input<string>? BasicAuthPassword { get; set; }

        [Input("clientSecret")]
        public Input<string>? ClientSecret { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("privateKey")]
        public Input<string>? PrivateKey { get; set; }

        [Input("secretKey")]
        public Input<string>? SecretKey { get; set; }

        [Input("sigv4AccessKey")]
        public Input<string>? Sigv4AccessKey { get; set; }

        [Input("sigv4SecretKey")]
        public Input<string>? Sigv4SecretKey { get; set; }

        [Input("tlsCaCert")]
        public Input<string>? TlsCaCert { get; set; }

        [Input("tlsClientCert")]
        public Input<string>? TlsClientCert { get; set; }

        [Input("tlsClientKey")]
        public Input<string>? TlsClientKey { get; set; }

        public DataSourceSecureJsonDataGetArgs()
        {
        }
        public static new DataSourceSecureJsonDataGetArgs Empty => new DataSourceSecureJsonDataGetArgs();
    }
}
