// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class MuteTimingIntervalArgs : global::Pulumi.ResourceArgs
    {
        [Input("daysOfMonths")]
        private InputList<string>? _daysOfMonths;
        public InputList<string> DaysOfMonths
        {
            get => _daysOfMonths ?? (_daysOfMonths = new InputList<string>());
            set => _daysOfMonths = value;
        }

        [Input("months")]
        private InputList<string>? _months;
        public InputList<string> Months
        {
            get => _months ?? (_months = new InputList<string>());
            set => _months = value;
        }

        [Input("times")]
        private InputList<Inputs.MuteTimingIntervalTimeArgs>? _times;
        public InputList<Inputs.MuteTimingIntervalTimeArgs> Times
        {
            get => _times ?? (_times = new InputList<Inputs.MuteTimingIntervalTimeArgs>());
            set => _times = value;
        }

        [Input("weekdays")]
        private InputList<string>? _weekdays;
        public InputList<string> Weekdays
        {
            get => _weekdays ?? (_weekdays = new InputList<string>());
            set => _weekdays = value;
        }

        [Input("years")]
        private InputList<string>? _years;
        public InputList<string> Years
        {
            get => _years ?? (_years = new InputList<string>());
            set => _years = value;
        }

        public MuteTimingIntervalArgs()
        {
        }
        public static new MuteTimingIntervalArgs Empty => new MuteTimingIntervalArgs();
    }
}
