// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class NotificationPolicyPolicyPolicyPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("contactPoint", required: true)]
        public Input<string> ContactPoint { get; set; } = null!;

        [Input("continue")]
        public Input<bool>? Continue { get; set; }

        [Input("groupBies", required: true)]
        private InputList<string>? _groupBies;
        public InputList<string> GroupBies
        {
            get => _groupBies ?? (_groupBies = new InputList<string>());
            set => _groupBies = value;
        }

        [Input("groupInterval")]
        public Input<string>? GroupInterval { get; set; }

        [Input("groupWait")]
        public Input<string>? GroupWait { get; set; }

        [Input("matchers")]
        private InputList<Inputs.NotificationPolicyPolicyPolicyPolicyMatcherGetArgs>? _matchers;
        public InputList<Inputs.NotificationPolicyPolicyPolicyPolicyMatcherGetArgs> Matchers
        {
            get => _matchers ?? (_matchers = new InputList<Inputs.NotificationPolicyPolicyPolicyPolicyMatcherGetArgs>());
            set => _matchers = value;
        }

        [Input("muteTimings")]
        private InputList<string>? _muteTimings;
        public InputList<string> MuteTimings
        {
            get => _muteTimings ?? (_muteTimings = new InputList<string>());
            set => _muteTimings = value;
        }

        [Input("policies")]
        private InputList<Inputs.NotificationPolicyPolicyPolicyPolicyPolicyGetArgs>? _policies;
        public InputList<Inputs.NotificationPolicyPolicyPolicyPolicyPolicyGetArgs> Policies
        {
            get => _policies ?? (_policies = new InputList<Inputs.NotificationPolicyPolicyPolicyPolicyPolicyGetArgs>());
            set => _policies = value;
        }

        [Input("repeatInterval")]
        public Input<string>? RepeatInterval { get; set; }

        public NotificationPolicyPolicyPolicyPolicyGetArgs()
        {
        }
        public static new NotificationPolicyPolicyPolicyPolicyGetArgs Empty => new NotificationPolicyPolicyPolicyPolicyGetArgs();
    }
}
