// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class OncallRouteSlackArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Slack channel id. Alerts will be directed to this channel in Slack.
        /// </summary>
        [Input("channelId", required: true)]
        public Input<string> ChannelId { get; set; } = null!;

        public OncallRouteSlackArgs()
        {
        }
        public static new OncallRouteSlackArgs Empty => new OncallRouteSlackArgs();
    }
}
