// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class OncallIntegrationDefaultRouteGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("escalationChainId")]
        public Input<string>? EscalationChainId { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("slack")]
        public Input<Inputs.OncallIntegrationDefaultRouteSlackGetArgs>? Slack { get; set; }

        public OncallIntegrationDefaultRouteGetArgs()
        {
        }
        public static new OncallIntegrationDefaultRouteGetArgs Empty => new OncallIntegrationDefaultRouteGetArgs();
    }
}
