// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class SyntheticMonitoringCheckSettingsArgs : global::Pulumi.ResourceArgs
    {
        [Input("dns")]
        public Input<Inputs.SyntheticMonitoringCheckSettingsDnsArgs>? Dns { get; set; }

        [Input("http")]
        public Input<Inputs.SyntheticMonitoringCheckSettingsHttpArgs>? Http { get; set; }

        [Input("ping")]
        public Input<Inputs.SyntheticMonitoringCheckSettingsPingArgs>? Ping { get; set; }

        [Input("tcp")]
        public Input<Inputs.SyntheticMonitoringCheckSettingsTcpArgs>? Tcp { get; set; }

        [Input("traceroute")]
        public Input<Inputs.SyntheticMonitoringCheckSettingsTracerouteArgs>? Traceroute { get; set; }

        public SyntheticMonitoringCheckSettingsArgs()
        {
        }
        public static new SyntheticMonitoringCheckSettingsArgs Empty => new SyntheticMonitoringCheckSettingsArgs();
    }
}
