// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getLibraryPanel(args?: GetLibraryPanelArgs, opts?: pulumi.InvokeOptions): Promise<GetLibraryPanelResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("grafana:index/getLibraryPanel:getLibraryPanel", {
        "name": args.name,
        "uid": args.uid,
    }, opts);
}

/**
 * A collection of arguments for invoking getLibraryPanel.
 */
export interface GetLibraryPanelArgs {
    name?: string;
    uid?: string;
}

/**
 * A collection of values returned by getLibraryPanel.
 */
export interface GetLibraryPanelResult {
    readonly created: string;
    readonly dashboardIds: number[];
    readonly description: string;
    readonly folderId: number;
    readonly folderName: string;
    readonly folderUid: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly modelJson: string;
    readonly name?: string;
    readonly orgId: number;
    readonly panelId: number;
    readonly type: string;
    readonly uid?: string;
    readonly updated: string;
    readonly version: number;
}

export function getLibraryPanelOutput(args?: GetLibraryPanelOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetLibraryPanelResult> {
    return pulumi.output(args).apply(a => getLibraryPanel(a, opts))
}

/**
 * A collection of arguments for invoking getLibraryPanel.
 */
export interface GetLibraryPanelOutputArgs {
    name?: pulumi.Input<string>;
    uid?: pulumi.Input<string>;
}
