// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOncallSlackChannel(args: GetOncallSlackChannelArgs, opts?: pulumi.InvokeOptions): Promise<GetOncallSlackChannelResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("grafana:index/getOncallSlackChannel:getOncallSlackChannel", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getOncallSlackChannel.
 */
export interface GetOncallSlackChannelArgs {
    name: string;
}

/**
 * A collection of values returned by getOncallSlackChannel.
 */
export interface GetOncallSlackChannelResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly slackId: string;
}

export function getOncallSlackChannelOutput(args: GetOncallSlackChannelOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOncallSlackChannelResult> {
    return pulumi.output(args).apply(a => getOncallSlackChannel(a, opts))
}

/**
 * A collection of arguments for invoking getOncallSlackChannel.
 */
export interface GetOncallSlackChannelOutputArgs {
    name: pulumi.Input<string>;
}
