// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class RuleGroup extends pulumi.CustomResource {
    /**
     * Get an existing RuleGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RuleGroupState, opts?: pulumi.CustomResourceOptions): RuleGroup {
        return new RuleGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'grafana:index/ruleGroup:RuleGroup';

    /**
     * Returns true if the given object is an instance of RuleGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RuleGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RuleGroup.__pulumiType;
    }

    /**
     * The UID of the group that the folder belongs to.
     */
    public readonly folderUid!: pulumi.Output<string>;
    /**
     * The interval, in seconds, at which all rules in the group are evaluated. If a group contains many rules, the rules are
     * evaluated sequentially.
     */
    public readonly intervalSeconds!: pulumi.Output<number>;
    /**
     * The name of the rule group.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The ID of the org to which the group belongs.
     */
    public readonly orgId!: pulumi.Output<number>;
    /**
     * The rules within the group.
     */
    public readonly rules!: pulumi.Output<outputs.RuleGroupRule[]>;

    /**
     * Create a RuleGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RuleGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RuleGroupArgs | RuleGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RuleGroupState | undefined;
            resourceInputs["folderUid"] = state ? state.folderUid : undefined;
            resourceInputs["intervalSeconds"] = state ? state.intervalSeconds : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["orgId"] = state ? state.orgId : undefined;
            resourceInputs["rules"] = state ? state.rules : undefined;
        } else {
            const args = argsOrState as RuleGroupArgs | undefined;
            if ((!args || args.folderUid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'folderUid'");
            }
            if ((!args || args.intervalSeconds === undefined) && !opts.urn) {
                throw new Error("Missing required property 'intervalSeconds'");
            }
            if ((!args || args.orgId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'orgId'");
            }
            if ((!args || args.rules === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rules'");
            }
            resourceInputs["folderUid"] = args ? args.folderUid : undefined;
            resourceInputs["intervalSeconds"] = args ? args.intervalSeconds : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["orgId"] = args ? args.orgId : undefined;
            resourceInputs["rules"] = args ? args.rules : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RuleGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RuleGroup resources.
 */
export interface RuleGroupState {
    /**
     * The UID of the group that the folder belongs to.
     */
    folderUid?: pulumi.Input<string>;
    /**
     * The interval, in seconds, at which all rules in the group are evaluated. If a group contains many rules, the rules are
     * evaluated sequentially.
     */
    intervalSeconds?: pulumi.Input<number>;
    /**
     * The name of the rule group.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the org to which the group belongs.
     */
    orgId?: pulumi.Input<number>;
    /**
     * The rules within the group.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.RuleGroupRule>[]>;
}

/**
 * The set of arguments for constructing a RuleGroup resource.
 */
export interface RuleGroupArgs {
    /**
     * The UID of the group that the folder belongs to.
     */
    folderUid: pulumi.Input<string>;
    /**
     * The interval, in seconds, at which all rules in the group are evaluated. If a group contains many rules, the rules are
     * evaluated sequentially.
     */
    intervalSeconds: pulumi.Input<number>;
    /**
     * The name of the rule group.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the org to which the group belongs.
     */
    orgId: pulumi.Input<number>;
    /**
     * The rules within the group.
     */
    rules: pulumi.Input<pulumi.Input<inputs.RuleGroupRule>[]>;
}
